### PR TITLE
Implement the remaining socket-related WASI functions.

### PR DESCRIPTION
**Pull request by sunfishcode**
The original WASI specification included `sock_read`, `sock_write`, and
`shutdown`. Now that we have some sockets support, implement these
additional functions, to make it easier for people porting existing code
to WASI.

It's expected that this will all be subsumed by the wasi-sockets
proposal, but for now, this is a relatively small change which should
hopefully unblock people trying to use the current `accept` support.

### CODE REVIEW

**Review by jameysharp — APPROVED** [review]
Looks right to me!

**Comment by sunfishcode** [comment]
Windows disagrees :upside_down_face:

**Comment by jameysharp** [comment]
I assume cargo-vet is going to need a delta audit for `system-interface`.

**Comment by stevelr** [comment]
I am not sure I see how sock_shutdown is intended to be used if the socket is in use by a wasm module.

Scenario: the host creates a tcp listener socket bound to an address, and adds it to `WasiCtx` as a `preopened_socket`.  The wasm module creates a listener via the wasi api and calls accept().

Sometime later, while wasm module is still waiting on `accept`, the host wants to stop the module. It can't directly call `sock_shutdown` because neither TcpListen nor Socket are cloneable, so it can't hold onto a cloned object to call shutdown on it later. If the host kept the u32 file descriptor, it could either recreate a Socket from the fd and call sock_shutdown, or pass the fd to a low-level unix function to close it, which seems extremely non-portable. There is a try_clone and if it succeeds it creates an alias file descriptor, but it's not clear from the documentation if it would work for this purpose.

What is the recommended method of closing a socket in this scenario?

**Comment by sunfishcode** [comment]
@stevelr shutdown doesn't do a close; it just marks a stream as no longer readable, writeable, or both. The file descriptor remains open. And it isn't required to be called.

The main use case for it that I know is for one side of a socket to declare that it's done writing to a stream and will subsequently only be reading the response.

**Pull request merged**
