### PR TITLE
Re-enable fuzzing in test-all.sh.

### LINKED ISSUE #1257: Should fuzzing be re-enabled in test-all.sh?
In #580, fuzzing was [disabled in the `test-all.sh` script](https://github.com/bytecodealliance/wasmtime/blob/fbe29da5cc1c0847af176f151f114a6a535534ff/scripts/test-all.sh#L79). Should it be re-enabled now that the [blocking issue](https://github.com/bytecodealliance/cranelift/issues/1216) is resolved?

CC @sunfishcode

### PR DESCRIPTION
**Pull request by sunfishcode**
Also remove testing for wasmtime-wasi-c testing, which is no longer in
the tree.

Fixes #1257.

cc @tschneidereit

### CODE REVIEW

**Comment by alexcrichton** [comment]
I don't think we actually use this script on CI, so should we remove the script? If not should we switch CI to running this script?

**Comment by sunfishcode** [comment]
It's not great to run a test-all.sh script in CI, because it means the CI has to treat it like one big command with a big log output that you have to wade through.

Is there a recommend way to do the opposite -- run the CI scripts locally?

**Comment by alexcrichton** [comment]
It's true yeah that it's not a great setup for CI, but if we don't actually run scripts like this on CI they inevitably break and fall out of date. In that sense if we want to keep it up to date I think we should run it on CI, otherwise I think we'll probably want to remove it since "test all" is "run ci" rather than running this script.

**Comment by sunfishcode** [comment]
This is no longer relevant.

**Pull request closed without merging**
