### PR TITLE
Cranelift AArch64: Fix the atomic memory operations

### PR DESCRIPTION
**Pull request by akirilov-arm**
Previously the implementations of the various atomic memory IR operations ignored the memory operation flags that were passed.

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
LGTM. I think removing the notion of sinking atomic loads is probably the right call as well. Thanks!

**Comment by cfallin** [comment]
Merged upstream into this PR after merge conflicts with #4830.

**Comment by cfallin** [comment]
(Actually disabling auto-merge here as I won't be around when it goes in and letting two run in parallel is risky; I'll merge this tomorrow.)

**Comment by akirilov-arm** [comment]
We still have the rule to sink an atomic load, it's just that the helper data structure and functions were unnecessary, save for a bit of ISLE code.

**Comment by cfallin** [comment]
> We still have the rule to sink an atomic load, it's just that the helper data structure and functions were unnecessary, save for a bit of ISLE code.

Ah, yes, I missed that but see it now, for the `(uextend (atomic_load ...))` case. Thanks!

**Pull request merged**
