### PR TITLE
wasi-c2 improvements

### PR DESCRIPTION
**Pull request by Ekleog**

### CODE REVIEW

**Comment by Ekleog** [comment]
Hey! I'm going to push to this branch the changes I find necessary to wasi-c2 as I go, feel free to merge if you want I'll just create another branch to keep adding things I'm missing :) and if there are changes you think wrong please let me know! (I originally thought this would only expose WasiCtxBuilder, but ended up going around the code and randomly seeing that preopening a dir without setting stdio would currently make the dir actually be stdio, which would likely end up in wrong behavior, so I drive-by sent this change too, though I'm unsure how to test it as CI's already broken on this branch)

**Comment by Ekleog** [comment]
Random question while I'm in the process of changing stuff: is the fact that there is no preopened_file that would allow preopening just a file on purpose? it doesn't look that awesome to use in practice, but maybe WASI doesn't support that yet?

**Comment by Ekleog** [comment]
Random thought: I'm thinking `preopened_dir` should have its arguments reversed, because in practice the path will often be shorter than opening the equivalent directory. WDYT?

**Comment by pchickey** [comment]
I'm happy for whatever improvements to the WasiCtxBuilder API, I've only used it in the test-programs harness so it is very poorly exercised. 

As far as CI goes - I've been testing by running `cargo test --features test_programs` from inside `crates/test-programs`. The known failures are in wasi-c2/TEST_FAILURES. It's sloppy, though, and once I have the scheduler working I'll pursue getting all of CI fixed.

**Pull request merged**
