### PR TITLE
Fix some `i128` shift-related bugs in x64 backend.

### LINKED ISSUE #2672: Cranelift: ishl.i8 with i128 shift amount panics
### Steps to Reproduce

Try to compile an `ishl` instruction with an `i8` lhs and `i128` rhs using the x64 backend.

### Expected Results

It compiles.

### Actual Results

Panics with `thread 'rustc' panicked at 'Multi-register value not expected', /home/bjorn/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/c07ec4c/cranelift/codegen/src/isa/x64/lower.rs:128:10`

### Versions and Environment

Cranelift version or commit: c07ec4c525318afb47b2c6ff24dcddb5d23b5f2a

Operating system: N/A

Architecture: x86_64

### PR DESCRIPTION
**Pull request by cfallin**
This fixes #2672 and #2679, and also fixes an incorrect instruction
emission (`test` with small immediate) that we had missed earlier.

The shift-related fixes have to do with (i) shifts by 0 bits, as a
special case that must be handled; and (ii) shifts by a 128-bit amount,
which we can handle by just dropping the upper half (we only use 3--7
bits of shift amount).

This adjusts the lowerings appropriately, and also adds run-tests to
ensure that the lowerings actually execute correctly (previously we only
had compile-tests with golden lowerings; I'd like to correct this for
more ops eventually, adding run-tests beyond what the Wasm spec and
frontend covers).

### CODE REVIEW

**Comment by bjorn3** [comment]
```
[legion/src/internals/insert.rs:54] component_index = 0
[legion/src/internals/insert.rs:54] 1u128 << dbg!(component_index) = 18446744073709551617
```

It didn't help unfortunately.

**Comment by cfallin** [comment]
Ah, yes, you were right; I confused `tmp2` for `tmp3` (a classic mistake!) and failed to actually use any test vectors with differing lower and upper halves. Should be fixed now (and added a few more test cases). Thanks!

**Review by bjorn3 — APPROVED** [review]
Thanks! This version works.

**Review by abrown — APPROVED** [review]
I think this looks fine. (As an aside, why aren't we using SSE2's `PSLLDQ`/`PSRLDQ` instructions instead of these long sequences? I haven't looked at much of the i128 code but it would seem that moving upper and lower halves to XMMs and back might still be faster for one of these cases?)

**Comment by cfallin** [comment]
> I think this looks fine. (As an aside, why aren't we using SSE2's `PSLLDQ`/`PSRLDQ` instructions instead of these long sequences? I haven't looked at much of the i128 code but it would seem that moving upper and lower halves to XMMs and back might still be faster for one of these cases?)

Ah, the simple answer is that I don't know SSE well enough to reach for such instructions -- though it looks like they should work much more efficiently than these sequences! I'll go ahead and merge with your +1 for now so that we have correct results; but we can definitely improve this later. Thanks!

**Pull request merged**
