### PR TITLE
cranelift: Added fp `and`, `or`, `xor`, `not` ops to interpreter.

### PR DESCRIPTION
**Pull request by ArtBlnd**
Tests are not ready. I'll add it ASAP.
@afonso360

### CODE REVIEW

**Review by afonso360 — APPROVED** [review]
This looks great to me! Just add the missing tests and we should be good to go.

Thanks for working on this!

**Comment by ArtBlnd** [comment]
Kinda struggling testing with NaNs. I think I can do in 3 days.

**Comment by ArtBlnd** [comment]
Ok, I've try testing this many times but I think its better testing with i32 to f32 bitcasts. to do that. we need to test `bitcast.i32` and `bitcast.f32` first before we go.

Thoughts?

**Comment by afonso360** [comment]
> Ok, I've try testing this many times but I think its better testing with i32 to f32 bitcasts. to do that. we need to implement and test bitcast.ixx and bitcast.fxx first before we go.

I don't mind the tests with bitcast -> op -> bitcast. But what issues are you seeing with just using floats in and out?

> also pretty much sure that fp bit ops should work like integer bit ops.

Agreed! I don't think any special input should cause us to deviate from that.

**Comment by ArtBlnd** [comment]
> I don't mind the tests with bitcast -> op -> bitcast (although I would slightly prefer them without). But what issues are you seeing with just using floats in and out?

We can't check sign value of float in NaN payload. I think its better using `bitcast` to test it.

**Comment by afonso360** [comment]
In our runtest suite we do bit comparisions of float output, so you should be able to pass in a `sNaN` and compare a `sNaN` output.

We do that in other tests, see for example `fcopysign` which is also a "bitwise" op: 
https://github.com/bytecodealliance/wasmtime/blob/a434f43d2276dd30dab26cfeaa4103f337557f17/cranelift/filetests/filetests/runtests/fcopysign.clif#L39-L55

**Comment by ArtBlnd** [comment]
Sorry for being late. I had other jobs to do last weekend.

**Comment by ArtBlnd** [comment]
Also I think this need rebase. reopening PR.

**Pull request closed without merging**
