### PR TITLE
Codegen fix  atomic_rmw_loop missing move result to `dst` register On riscv64.

### PR DESCRIPTION
**Pull request by yuyang-ok**
This will fix https://github.com/bytecodealliance/wasmtime/issues/5884.
I forget move   the result to `dst` register.

### CODE REVIEW

**Comment by jameysharp** [comment]
This is failing the test in `tests/spec_testsuite/proposals/threads/atomic.wast` on line 142, because `atomic_rmw` is expected to return the _old_ value at the address, not the newly-written value.

To fix #5884, I think you should write the result of `AtomicOP::extract` to `dst` instead of writing it to `t0`, and update later instructions accordingly.

**Comment by yuyang-ok** [comment]
@jameysharp , Thanks, The `atomic_rmw_loop ` kinda of little complex. I think I want  to recheck it when I have time.

**Comment by jameysharp** [comment]
Yeah, I had a difficult time understanding what the loop was doing. I suspect we can improve it, and I'd be happy to discuss it further when you have time.

**Comment by yuyang-ok** [comment]
@jameysharp sure.

**Comment by yuyang-ok** [comment]
There is a `CI` failure Without errors.

**Comment by jameysharp** [comment]
I tried re-running just the failed CI jobs, but then extra jobs ran, which failed without useful logs, and I don't understand why. I'll have to look into this again next week if nobody else gets to it first.

**Comment by yuyang-ok** [comment]
@jameysharp Ok,thanks.

**Review by afonso360 — APPROVED** [review]
This looks correct to me though the whole thing is a little bit complex!

I've re-ran CI, and it looks like its just failing on s390x. Probably due to us relying on the native endianness!

We can change the test to be explicit about `little` and it starts passing.

<details>
<summary>New Testcase</summary>

```
test run
target aarch64
target x86_64
target riscv64
target s390x


function %a(i64, i16) -> i16 {
    ss0 = explicit_slot 8

block0(v0: i64, v1: i16):
    v2 = stack_addr.i64 ss0+0
    store little v0, v2

    v3 = stack_addr.i64 ss0+6
    v4 = atomic_rmw.i16 little or v3, v1
    return v4
}

; run: %a(8608481011852310776, 0) == 30583
```

</details>

**Comment by yuyang-ok** [comment]
@afonso360 Thanks.

**Comment by yuyang-ok** [comment]
@afonso360 I think we are ready.

**Comment by afonso360** [comment]
Sorry! Forgot to check back on this!

**Pull request merged**
