### PR TITLE
style: simplify string formatting

### PR DESCRIPTION
**Pull request by hamirmahal**
This change cleans up parts of the codebase for readability and maintainability.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Thanks for this! 

Out of curiosity how did you detect these cases? Is this perhaps a compiler lint or a clippy lint?

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
I use stricter `clippy` checks, like `clippy::pedantic`.

**Comment by alexcrichton** [comment]
Oh nice! If you'd like feel free to add this lint [here](https://github.com/bytecodealliance/wasmtime/blob/ba864e987ef1ab87c439ca6b396264547d2425e1/Cargo.toml#L174-L182) which would be a ratchet for the whole workspace. Probably not all of `pedantic` but this specific lint I think would be a reasonable candidate to add.

**Pull request merged**
