### PR TITLE
[lightbeam] Refactoring Error handling + remove panicking calls in lightbeam backend

### PR DESCRIPTION
**Pull request by pventuzelo**
Hi guys,

I triggered some new bugs during fuzzing of lightbeam. Those bugs are mainly related to usage of unreachable! and expect.
I remove a lot of the panic!, assert!, expect, etc. from `backend.rs` and `function_body.rs`. Removing all those calls make me refactoring completely the Error handling of `backend.rs` as well as some modification in `function_body.rs` i.e. that's why it's a huge PR.

Related bugs:
- https://github.com/bytecodealliance/wasmtime/issues/673
- https://github.com/bytecodealliance/wasmtime/issues/674

This code has been successfully tested with: `cargo test --release --features lightbeam`

### CODE REVIEW

**Comment by pventuzelo** [comment]
Any ETA for review/merging? 
Do you need something from my side?

**Comment by Robbepop** [comment]
> Any ETA for review/merging?
> Do you need something from my side?

I guess it is hindersome to review this PR as long as CI fails for it, especially the Lightbeam CI is failing, indicating that something is off.

**Comment by pventuzelo** [comment]
> > Any ETA for review/merging?
> > Do you need something from my side?
> 
> I guess it is hindersome to review this PR as long as CI fails for it, especially the Lightbeam CI is failing, indicating that something is off.

CI seems to failed when lightbeam feature is excluded. so it's maybe more related to wasi in that case.

For the tests on macos, there is not output, it's strange.
Do you know if there is any issue with CI?

**Comment by Robbepop** [comment]
> > > Any ETA for review/merging?
> > > Do you need something from my side?
> > 
> > 
> > I guess it is hindersome to review this PR as long as CI fails for it, especially the Lightbeam CI is failing, indicating that something is off.
> 
> CI seems to failed when lightbeam feature is excluded. so it's maybe more related to wasi in that case.
> 
> For the tests on macos, there is not output, it's strange.
> Do you know if there is any issue with CI?

I don't know of any CI bugs but also I am not a wasmtime maintainer - just filed my own first PR here but it passes CI.
Maybe a wasmtime team member could politely restart the CI for this branch to see if it was just an error.

**Comment by pventuzelo** [comment]
> > > > Any ETA for review/merging?
> > > > Do you need something from my side?
> > > 
> > > 
> > > I guess it is hindersome to review this PR as long as CI fails for it, especially the Lightbeam CI is failing, indicating that something is off.
> > 
> > 
> > CI seems to failed when lightbeam feature is excluded. so it's maybe more related to wasi in that case.
> > For the tests on macos, there is not output, it's strange.
> > Do you know if there is any issue with CI?
> 
> I don't know of any CI bugs but also I am not a wasmtime maintainer - just filed my own first PR here but it passes CI.
> Maybe a wasmtime team member could politely restart the CI for this branch to see if it was just an error.

Thanks for your help ;)

I've update wasmparser to last version and correct the error due to refactoring of wasmparser in this commit https://github.com/bytecodealliance/wasmparser/commit/86431440269a33af5f7c6ca887a2718b4283d27b

Maybe that's why wasi tests don't pass.

**Comment by pventuzelo** [comment]
Nice so everything good ;)

**Comment by Robbepop** [comment]
CI seems to be happy now.
I will review this PR later today.

**Comment by pventuzelo** [comment]
> CI seems to be happy now.
> I will review this PR later today.
> Can you resolve the conflicts with master branch before?
> My PR just got merged that also already updated to wasmparser 0.44 - I guess that's why there are conflicts now.

Yes i'm working on the conflicts right now.
I let you know when it's done ;)

**Comment by pventuzelo** [comment]
@Robbepop  Everything seems good ;)

**Comment by pventuzelo** [comment]
@alexcrichton @sunfishcode seems that the CI for .NET bindings can't start properly.
It failed on `Run /./.github/actions/install-rust`.

Can you restart the CI?

**Comment by sunfishcode** [comment]
Ok, I've now clicked the button to re-run the tests.

**Comment by pventuzelo** [comment]
@sunfishcode Thx, everything seems good now.

**Comment by Vurich** [comment]
Could you switch to using proper error types please? Here's a good overview of crates in the ecosystem to define error types https://users.rust-lang.org/t/the-state-of-error-handling-in-the-2018-edition/23263

Apart from that this seems good and ready to merge.

**Comment by pventuzelo** [comment]
We discuss about error types with @Vurich, and it seems better to merge the current pull request and then create a new one only for error types uniformisation.

**Pull request merged**
