### PR TITLE
bump cranelift version to 0.60.0

### PR DESCRIPTION
**Pull request by froydnj**
Some recent changes are needed for Lucet changes.

### CODE REVIEW

**Comment by froydnj** [comment]
(I don't have the bit to actually publish to crates.io, somebody else will have to do that part.)

**Comment by fitzgen** [comment]
I can do the publish.

**Comment by froydnj** [comment]
How important are the CI failures?  I see that a number of recent PRs have been getting merged with red CI, but I'm not well versed in what's liable to fail and what's not...

**Comment by pchickey** [comment]
Can you hold this until #1311 is in? It had a failure on nightly only, I just rebased and force-pushed with hope that whatever was wrong with CI is fixed now

**Comment by fitzgen** [comment]
Yeah, our CI setup is acting a bit flaky at the moment. I'm not sure what our policy on merging PRs is until we fix it. It seems like it might make sense to delay publishing releases until we know our CI is green...

**Comment by froydnj** [comment]
> Can you hold this until #1311 is in? It had a failure on nightly only, I just rebased and force-pushed with hope that whatever was wrong with CI is fixed now

Sure, no problem!

**Comment by pchickey** [comment]
https://github.com/bytecodealliance/wasmtime/pull/1330 should help us make more sense of the CI failures.

**Comment by pchickey** [comment]
btw https://github.com/bytecodealliance/wasmtime/pull/1311 is merged so no more delay required there

**Comment by fitzgen** [comment]
I will do the publish and verify that the re-added publish script works.

**Comment by fitzgen** [comment]
Published!

**Pull request merged**
