### PR TITLE
c-api: add wasm_config_parallel_compilation_set

### PR DESCRIPTION
**Pull request by thibaultcha**
This has not been discussed in issues and I do not believe there are tests cases for the config C API. Nevertheless, could we add this flag in the C API with this small changeset?

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Looks good to me, thanks!

**Comment by thibaultcha** [comment]
Can we restart the CI on this one? I don't think the failures are related; and we'd really like this being part of the next release if possible so that we don't lag too far behind the latest Wasmtime version...

**Comment by alexcrichton** [comment]
Oh sorry missed the updates here, could you try rebasing? That known flaky test has been fixed on `main`

**Comment by thibaultcha** [comment]
Ah, excellent, done!

**Pull request merged**
