### PR TITLE
debug: Avoid underflow when scanning for landing pad bytes

### PR DESCRIPTION
**Pull request by bnjbvr**
I don't really know what I'm doing here, but bear with me... This landing pad bytes scanning assumes at least 2 bytes in the given buffer, but in a local test case I was trying against, the buffer was empty, so 0 bytes, so the subtract would underflow. Just adding this guard seems to make it work-ish -- I don't get full variable inspection power, but I expect that this is unrelated to my change.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Do you know if it would be possible to add a test for this?

**Comment by bnjbvr** [comment]
Unfortunately, it's a very very large module, hard to break up. If you've got a tool or a magic command line that can take the wat and automatically reduce it, I'm willing to try it. Unfortunately I don't know enough about this code so as to be able to craft a test case from scratch.

**Comment by alexcrichton** [comment]
Ah ok, seems fine then!

**Comment by bjorn3** [comment]
You could try creduce on the `.wat` file. Creduce works relatively well on anything that even remotely looks like C. Wat having paired parens should be C like enough for it to work.

**Pull request merged**
