### PR TITLE
Fix the order of the rex2 registers for r_ib_unsigned_gpr

### LINKED ISSUE #1423: Cranelift: x86_pextr encoding using wrong source register %xmm7 instead of %xmm15
I compiled

```
test compile
set enable_simd
target x86_64-unknown-linux-gnu haswell

function u0:0() -> i32 system_v {
    ss0 = explicit_slot 32
    sig0 = () system_v
    fn0 = colocated u0:2 sig0

block0:
    v0 = stack_addr.i64 ss0
    v1 = load.i32x4 v0
    call fn0()
    v2 = extractlane.i32x4 v1, 1
    return v2
}
```

this results in the following ir after regalloc:

```
function u0:0(i64 fp [%rbp]) -> i32 [%rax], i64 fp [%rbp] system_v {
    ss0 = explicit_slot 32, offset -48
    ss1 = spill_slot 16, offset -64
    ss2 = incoming_arg 16, offset -16
    sig0 = () system_v
    fn0 = colocated u0:2 sig0

                                block0(v5: i64 [%rbp]):
[RexOp1pushq#50]                    x86_push v5
[RexOp1copysp#8089]                 copy_special %rsp -> %rbp
[RexOp1adjustsp_ib#d083]            adjust_sp_down_imm 48
[RexOp1spaddr8_id#808d,%rax]        v0 = stack_addr.i64 ss0
[DynRexOp2fld#410,%xmm0]            v3 = load.i32x4 v0
[RexOp2fspillSib32#411,ss1]         v1 = spill v3
[Op1call_id#e8]                     call fn0()
[RexOp2ffillSib32#410,%xmm15]       v4 = fill v1
[DynRexMp3r_ib_unsigned_gpr#d16,%rax] v2 = x86_pextr v4, 1
[RexOp1adjustsp_ib#8083]            adjust_sp_up_imm 48
[RexOp1popq#58,%rbp]                v6 = x86_pop.i64 
[Op1ret#c3]                         return v2, v6
}
```

The value passed to `x86_pextr` is stored in `%xmm15`, however the resulting asm expects it in `%xmm7` despite actually being filled to the correct `%xmm15`:

```asm
   0:   40 55                   push    rbp
   2:   48 89 e5                mov     rbp, rsp
   5:   48 83 ec 30             sub     rsp, 0x30
   9:   48 8d 84 24 10 00 00 00 lea     rax, [rsp + 0x10]
  11:   0f 10 00                movups  xmm0, xmmword ptr [rax]
  14:   40 0f 11 84 24 00 00 00 00
                                movups  xmmword ptr [rsp], xmm0
  1d:   e8 00 00 00 00          call    0x22
  22:   44 0f 10 bc 24 00 00 00 00
                                movups  xmm15, xmmword ptr [rsp]
  2b:   66 41 0f 3a 16 f8 01    pextrd  r8d, xmm7, 1
  32:   48 83 c4 30             add     rsp, 0x30
  36:   40 5d                   pop     rbp
  38:   c3                      ret
```

(Experimenting with SIMD support for cg_clif)

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #1423

r? @abrown

### CODE REVIEW

**Comment by bjorn3** [comment]
https://github.com/bytecodealliance/wasmtime/issues/1423#issuecomment-605295620

> Could you add an x86_pextr binemit test

Is the last commit ok, or do you want to test more cases?

**Comment by bjorn3** [comment]
With this I can finally store SIMD vectors in SSA values, rather than memory. This improves performance for tokei from ~50% overhead compared to cg_llvm to ~30% overhead.

**Comment by abrown** [comment]
I don't know if this will give you more flexibility, but note that in #1377 I have added support for declaring constants in the function preamble instead of only through `vconst`. This also should make it easier to use constants of sizes other than 128-bit. Take a look at 
64c8cbf and let me know if you can think of any changes to that that would help cg_clif.

**Comment by bjorn3** [comment]
I don't think any of that PR will help me. At least for now. Creating SIMD values is currently very slow anyway as at MIR level all lanes get assigned separately, meaning that I have to use `vconst 0` + `insertlane`. I will obviously need to optimize this :)

**Pull request merged**
