### PR TITLE
Atomic hotswapping in JIT mode

### PR DESCRIPTION
**Pull request by bjorn3**
May conflict with #2745 or #2750, so please merge those first.

### CODE REVIEW

**Comment by bjorn3** [comment]
Writing the GOT entries needs to be delayed until after relocations have been performed and the memory has been marked as executable for code or read only for read only data.

**Comment by bjorn3** [comment]
> Writing the GOT entries needs to be delayed until after relocations have been performed and the memory has been marked as executable for code or read only for read only data.

@eggyal has implemented this. Thanks!

**Comment by eggyal** [comment]
I think I may have made a mess here... 3e11bd8 is undoing much of 2d9190d.  While the result is that GOT updates are correctly deferred, which is what we needed for bjorn3/rustc_codegen_cranelift#1166, it likely isn't doing what's needed for hot swapping.  Let me take another look.

**Review by abrown — APPROVED** [review]
Looks OK to me but I'll defer to @sunfishcode if he has any comments.

**Pull request merged**
