### PR TITLE
A bunch of cleanups for cranelift-codegen-meta

### PR DESCRIPTION
**Pull request by bjorn3**
Followup to https://github.com/bytecodealliance/wasmtime/pull/6767

### CODE REVIEW

**Comment by jameysharp** [comment]
Most of these changes seem entirely reasonable to me, but I want to think about the cranelift-codegen-shared bits more.

**Comment by bjorn3** [comment]
Do you want me to split the cranelift-codegen-shared removal into a separate PR?

**Comment by jameysharp** [comment]
If you'd like to split it I'm happy to merge the rest today and take a little longer to think about that part.

**Comment by bjorn3** [comment]
Split out https://github.com/bytecodealliance/wasmtime/pull/6773

**Review by jameysharp — APPROVED** [review]
Thank you!

**Pull request merged**
