### PR TITLE
Fix srem.{i8,i16}

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes one half of #2826.

### CODE REVIEW

**Comment by bjorn3** [comment]
Doc failure is unrelated.

**Comment by bjorn3** [comment]
Nightly seems to break things.

**Review by cfallin — APPROVED** [review]
Thanks!

**Comment by cfallin** [comment]
Just fixed CI in #2830 -- if you rebase on top of that, I think CI should be fixed here.

**Pull request merged**
