### PR TITLE
PCC: x64: insertlane instructions read only scalar-sized values.

### PR DESCRIPTION
**Pull request by cfallin**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67538.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Mind adding more variants for loading floats, in addition to the variants for storing everything?

```wasm
(module
  (memory 1)
  (func (param v128 i32) (result v128)
      local.get 0
      local.get 1
      f32.load
      f32x4.replace_lane 0)

  (func (param v128 i32) (result v128)
      local.get 0
      local.get 1
      f64.load
      f64x2.replace_lane 1)

  (func (param v128 i32) (result v128)
      local.get 0
      local.get 1
      f64.load
      f64x2.replace_lane 0)

  (func (param v128 i32)
      local.get 1
      local.get 0
      f64x2.extract_lane 1
      f64.store)

  (func (param v128 i32)
      local.get 1
      local.get 0
      f32x4.extract_lane 1
      f32.store)

  (func (param v128 i32)
      local.get 1
      local.get 0
      i8x16.extract_lane_s 1
      i32.store8)

  (func (param v128 i32)
      local.get 1
      local.get 0
      i16x8.extract_lane_s 1
      i32.store16)

  (func (param v128 i32)
      local.get 1
      local.get 0
      i32x4.extract_lane 1
      i32.store)

  (func (param v128 i32)
      local.get 1
      local.get 0
      i64x2.extract_lane 1
      i64.store)
)
```

**Comment by alexcrichton** [comment]
Also I'd recommend running the test with/without AVX to confirm that that all works too

**Review by fitzgen — APPROVED** [review]
r=me with Alex's suggestion

**Comment by fitzgen** [comment]
race

**Review by fitzgen — APPROVED** [review]

**Pull request merged**
