### PR TITLE
cranelift: Introduce a feature to enable `trace` logs

### PR DESCRIPTION
**Pull request by bnjbvr**
- First commit introduces a Cargo feature (disabled by default) to enable/disable trace logs in cranelift-codegen, as well as a macro that will call into `log::trace` only if the feature is enabled, following exactly what regalloc2 does. If downstream users set their `log::max_level` to `Trace`, they would pay the cost for the logging infrastructure, even if the logger eventually decides to throw away the logs' contents, so it's better overall to not call into the logging infra at all.
- Second commit: previously disassembly was emitted if explicitly enabled (only in testing setups), or when the log level was debug or more. I suppose this was done during hacking on regalloc2 (as the commit introducing this change is the switch to regalloc2), and never reverted, so I've done that here. We could add a cranelift flag to be able to request that at runtime with the CLI, if needs be.

With this change and those from other PRs, there's no more meaningful difference between a Wasmtime embedding setting the log's max level to trace or above.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Also apologies for the broken CI, but if you rebase it should be back-to-green.

**Comment by bnjbvr** [comment]
> To confirm, does this problem stem from the desire to enable trace logging for some modules in your program, but not the cranelift modules?

Yes indeed.

> In such a situation is the logging framework's implementation of "no, don't actually emit this trace log" for the cranelift crates too expensive?

Yes, specifically we create something that we feed the `log` calls (and that's the expensive part here), but then the logger implementation decides to throw it away based on its own configuration.

**Review by cfallin — APPROVED** [review]
Sorry, I left this hanging and missed it on my review queue. This looks good!

**Comment by cfallin** [comment]
I think it needs a rebase again now that #4553 merged; happy to merge once that is in.

**Comment by bnjbvr** [comment]
This now passes CI and as there wasn't any pending comment, will merge. Thanks for the review!

**Pull request merged**
