### PR TITLE
Cranelift: Derive `Copy` for `InstructionData`

### PR DESCRIPTION
**Pull request by fitzgen**
And update `clone` calls to be copies.

### CODE REVIEW

**Comment by jameysharp** [comment]
Oh, one more thought: maybe hold off merging this until Chris gets to merge the egraph PR, because I'm pretty sure it'll have mild conflicts and I don't want him to have to rebase again. :sweat_smile:

**Comment by fitzgen** [comment]
@cfallin should I hold off on landing this until after the e-graphs PR?

**Comment by fitzgen** [comment]
> Maybe also add a test that `InstructionData` is 16 bytes (like the comment above it claims)?

Done.

**Comment by cfallin** [comment]
> @cfallin should I hold off on landing this until after the e-graphs PR?

Yes please, if you don't mind! It will hopefully merge today (if review finishes out well) and while this is a small PR, it will conflict with my code motion I think and I've rebased a bunch of times already...

**Pull request merged**
