### PR TITLE
Add test for filestat_get for stdio

### PR DESCRIPTION
**Pull request by sakarias88**
Adding tests as discussed in issue #2515.

### CODE REVIEW

**Comment by sakarias88** [comment]
@pchickey

**Comment by sakarias88** [comment]
We will fix the CI failures once we get our hands on a windows machine.

**Comment by abbec** [comment]
"Fixing up" fstat for Windows brought a question. It seems that the fstat implementation for Windows returns a lot of OS-specific information causing a WASI `fstat` call to behave differently depending on host OS. I thought the intention was that `fstat` for example was supposed to return information from a "WASI" perspective. I.e. for example the inode number would be an "emulated" inode number that is the same on both Unix and Windows hosts (which is not the case in Wasmtime currently but it is in Wasmer)?

**Comment by alexcrichton** [comment]
This is pretty dated at this point so I'm going to close this. Lots about WASI has additionally changed in the intervening time. To the extent that it's nice to have more tests I think it'd still be good to add tests for this, but that's probably best done in a fresh PR.

**Pull request closed without merging**
