### PR TITLE
Switch to `x64_rbp` to avoid the use of a pinned register

### PR DESCRIPTION
**Pull request by elliottt**
Avoid a use of `preg_rpb` in the x64 backend, using `x64_rbp` instead.

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
:+1:

**Comment by elliottt** [comment]
@fitzgen there was a test failure due to output differences with `get_frame_pointer`. This pr introduces an indirection through `%rdi` on the `fp_sp_pc.clif` test.

**Comment by jameysharp** [comment]
What is the `MovPReg` instruction doing? Is it possible to ensure it doesn't emit any instructions in cases like `fp_sp_pc.clif`? I hoped it would just impose a register constraint.

**Comment by cfallin** [comment]
> What is the `MovPReg` instruction doing? Is it possible to ensure it doesn't emit any instructions in cases like `fp_sp_pc.clif`? I hoped it would just impose a register constraint.

It always emits a move; unfortunately this is required, and the register constraint approach is not possible, because the register (rbp) is not otherwise allocatable. We can't let regalloc decide that the new vreg that was copied from rbp now lives in rbp; the original value in rbp is still live, but that's not tracked by regalloc.

**Review by jameysharp — APPROVED** [review]
Given Chris' explanation, this makes sense to me and I guess is the best we can do.

**Pull request merged**
