### PR TITLE
cranelift: Implement PartialEq on Ieee{32,64}

### LINKED ISSUE #4828: cranelift-fuzzgen fuzzbug: fcmp gives wrong answer on NaN
Original report: https://oss-fuzz.com/testcase-detail/5662899036618752

<details>
<summary>Test case input</summary>

```
YWlzY3RuIG8BXQAAe/HfLJGaiKD4/wAA6bZjQHhAcB7//wAHAAAA6bYgJgAB6fgAAAABAABK//8A
ABgAAAD/////f///////////////////////////////////////////////////////////////
/////////////////ydV1sbWP9aCKgKCtgoFAGUAAAAAAAAAm/4p2gFG8J19fQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAABlAWzzxkbacCrdpP//AAAAAAD6/wBDQ0P///////////////////////8A
ZcYNRyYxRvSWnfAyAAAAADsgAakAfX0AAP+udf8AAA8AAAAAAPr/AENDQ0NDm5ubm5ubm5ubm5ub
m5ubm5ubm5ubm5ubfX3zfZubfQ==
```

</details>

I've minimized this to the following CLIF test:

```
test interpret 
test run
target aarch64
target s390x
target x86_64

function %fn(f64 uext) -> b1 system_v {

block0(v3: f64):
    v78 = fcmp le v3, v3
    return v78
}

; run: %fn(-NaN:0x7ffffffffffff) == false
```

On x86-64, this call returns `false`; but on the interpreter it returns `true`. Those two implementations have disagreed at least back to June, so this doesn't seem to be due to any recent changes.

I wasn't sure what the "right" answer is here so I wrote a quick wasm program for which wasmtime generates this CLIF instruction.

<details>
<summary>Equivalent wasm</summary>

```
(module
  (func $fn (param f64) 
    local.get 0
    local.get 0
    f64.le
    if 
      unreachable
    end
  )
  (func $test
    f64.const -nan:0x7ffffffffffff
    call $fn
  )     
  (export "test" (func $test))
)       
```
</details>

This program doesn't trap either on wasmtime compiling for x86-64, or on wabt's wasm-interp, so I gather the Cranelift interpreter is the one giving the wrong answer here.

@afonso360, can you look into this?

I guess we should extend `cranelift/filetests/filetests/runtests/fcmp.clif` with NaN tests, and also start running that test file on the interpreter.

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

This fixes #4828 by implementing `PartialEq` in terms of float values for the `Ieee{32,64}` types.

Previously `PartialEq` was auto derived. This means that it was implemented in terms of `PartialEq` in a `u32`.

This is not correct for floats because `NaN != NaN`.

`PartialOrd` was manually implemented in 6d50099816f397c1ff3256d30f742cf041d54e32, but it seems like it was an oversight to leave `PartialEq` out until now.

The test suite depends on the previous behaviour so we adjust it to keep comparing bits instead of floats.

cc: @jameysharp

### CODE REVIEW

**Comment by afonso360** [comment]
For anyone else wondering why we use `Ieee{32,64}` like I was (since it looks like we are just slowly reimplementing `f32/f64`). I found this thread https://github.com/bytecodealliance/wasmtime/pull/2251#discussion_r498508646 where it appears that some arches (x86) may silence sNaN's

**Review by jameysharp — APPROVED** [review]
Fantastic work here, Afonso. Every question I had was already answered either by a comment in the code or by your PR comments; you've already opened an issue about the unimplemented aarch64 comparisons; and you've dramatically expanded the test cases for `fcmp`.

Now I want a comment on `Ieee32`/`Ieee64` pointing at the discussion you found, but I'm too excited to merge this to wait for that. :grin:

**Comment by jameysharp** [comment]
Awww, cranelift-fuzzgen needs a fix similar to the test suite runner, because it also expects bitwise equality for NaNs when comparing results.

**Comment by afonso360** [comment]
Huh, that is true! I was thinking about implementing a wrapper type over `Vec<DataValue>` like `RunResult` or something like that so that we don't have to duplicate the comparison function, what do you think about that?

**Comment by jameysharp** [comment]
I have a fix I'm testing now. I've added a `bitwise_eq` method to `DataValue` to share most of the logic. Then in cranelift-fuzzgen I've implemented `PartialEq` on `RunResult` in terms of `bitwise_eq`, and written similar code in `compare_results`. I don't feel bad about duplicating `l.len() == r.len() && l.iter().zip(r).all(|(l, r)| l.bitwise_eq(r))`.

**Comment by afonso360** [comment]
Hah! We implemented the same thing!

image


Down to the same name and everything!

**Comment by jameysharp** [comment]
Hah, nice! Ooh, I like your doc comment better than mine though. :grin:

BTW I only noticed while looking into this that `compare_results` doesn't check if the vectors have the same length. Maybe there's a check earlier that makes it unnecessary? But anywhere I see `.zip`, if different lengths could matter then I like to see an explicit check.

Do you want to open a PR for this? Here's the key bit I did in cranelift-fuzzgen:

```rust
impl PartialEq for RunResult {
    fn eq(&self, other: &Self) -> bool {
        if let (RunResult::Success(l), RunResult::Success(r)) = (self, other) {
            l.len() == r.len() && l.iter().zip(r).all(|(l, r)| l.bitwise_eq(r))
        } else {
            false
        }
    }
}
```

Then remove the `RunResult::unwrap` implementation and just do `assert_eq!(int_res, host_res);` at the end.

**Comment by alexcrichton** [comment]
FYI I think this is the cause of https://github.com/bytecodealliance/wasmtime/issues/4857

**Pull request merged**
