### PR TITLE
Cranelift DFG: make inst clone deep-clone varargs lists. 

### PR DESCRIPTION
**Pull request by cfallin**
When investigating #5716, I found that rematerialization of a `call`, in
addition to blowing up for other reasons, caused aliasing of the varargs
list (the `EntityList` in the `ListPool`), such that editing the args of
the second copy of the call instruction inadvertently updated the first
as well.

This PR modifies `DataFlowGraph::clone_inst` so that it always clones
the varargs list if present. This shouldn't have any functional impact
on Cranelift today, because we don't rematerialize any instructions with
varargs; but it's important to get it right to avoid a bug later!

### CODE REVIEW

**Comment by cfallin** [comment]
(Rebased to unstack from #5726; there's no need to couple these actually)

**Comment by jameysharp** [comment]
Can we generate an `InstructionData::deep_clone` method in the meta crate by looking at which formats have value-list operands? I'm worried this won't get updated as new formats are added.

The same issue applies to `BlockCall`, right?

Aside from bugs like #5726 the egraphs code currently can never hit any of these cases, right? I think all the instructions that use value-lists (just block terminators and calls I think) are impure and so are not currently duplicated.

**Comment by cfallin** [comment]
> Can we generate an InstructionData::deep_clone method in the meta crate by looking at which formats have value-list operands? I'm worried this won't get updated as new formats are added.

Yep, that's the better approach; I'll build that out.

> The same issue applies to BlockCall, right?

Ah, yes, indeed, I'll need to fix that too!

> Aside from bugs like #5726 the egraphs code currently can never hit any of these cases, right? I think all the instructions that use value-lists (just block terminators and calls I think) are impure and so are not currently duplicated.

Yep, there's no functional impact today; all pure insts happen to have fixed args.

**Review by jameysharp — APPROVED** [review]
Yeah, this seems entirely sensible. Thanks!

**Pull request merged**
