### PR TITLE
Fix popcnt for small integers

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes https://github.com/bytecodealliance/wasmtime/issues/3615

### CODE REVIEW

**Comment by cfallin** [comment]
Thanks! Can you add some run-tests too?

**Comment by bjorn3** [comment]
Done. Also made the existing aarch64 popcnt tests run on x86_64.

**Review by cfallin — APPROVED** [review]
Awesome, thank you!

**Comment by bjorn3** [comment]
Would it be possible to get a patch release with https://github.com/bytecodealliance/wasmtime/pull/3610, this PR and maybe https://github.com/bytecodealliance/wasmtime/pull/3619? #3610 and this PR fix a miscompilation and I switched cg_clif back to crates.io releases after feedback from my PR to distribute cg_clif as rustup component on nightly.

**Comment by cfallin** [comment]
> Would it be possible to get a patch release 

Yes, I think actual miscompilation merits this (for clarity to others, Wasm is not affected, just 8/16-bit types). I'll give our new [semi-automated patch release process](https://github.com/bytecodealliance/wasmtime/blob/main/docs/contributing-release-process.md#releasing-a-patch-release) a try; right now this implies a patch release of Wasmtime as well, which will be a no-op, and we need a better story for just patching Cranelift in the future, but this will do. If there's some unexpected issue and I can't get it out in reasonable time today then the next major release on Jan 5 will include all the changes.

**Pull request merged**
