### PR TITLE
update WASI submodule

### PR DESCRIPTION
**Pull request by cratelyn**
This PR updates our assorted `witx` dependencies to 0.9.1, which includes an important bug fix. See WebAssembly/WASI#434 for more information.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! FWIW the location of the `WASI` submodule is pretty finnicky especially when it comes to publishing to crates.io. For the easiest time updating I'd recommend updating it in-place if possible

**Comment by cratelyn** [comment]
> Thanks! FWIW the location of the `WASI` submodule is pretty finnicky especially when it comes to publishing to crates.io. For the easiest time updating I'd recommend updating it in-place if possible

Thanks @alexcrichton! I'll give that another go, moving the submodule was motivated by errors I was seeing that looked like a variation of rust-lang/cargo#6745. I wasn't able to `exclude` that directory from the root workspace, so commands like `cargo build` were failing due to multiple workspace roots being found.

**Comment by cratelyn** [comment]
```
error: multiple workspace roots found in the same workspace:
  /home/katelyn/fsly/wasmtime/crates/wasi-common/WASI/tools/witx
  /home/katelyn/fsly/wasmtime
```

For reference, this is the error I am seeing after updating the WASI submodule. I believe it's because of the `witx-cli` changes in WebAssembly/WASI#398 playing poorly with structure of this project.

**Comment by alexcrichton** [comment]
Oh dear... I think there's probably three ways to fix this:

1. Remove the workspace changes to the WASI repository, enabling integration here the same as before.
2. Fix the issues after moving this `vendor` dir around (I don't know off-hand how hard this would be)
3. Depend on the crates.io version of `witx`, not a git submodule. I think that this would require doing the same steps from (2), but we could just avoid a git submodule.

The easiest is probably the first one here, and the best is probably the 3rd, but that requires changes of how we integrate the WASI spec updates into this repository, since I think we rely on them existing in the `wasi-common` crate but now they'd be stored in the `witx` crate itself (I think?) published to crates.io

**Comment by alexcrichton** [comment]
Hm actually scratch that I don't think the `witx` crate as published to crates.io contains the wasi snapshot witx files. Sorry for this mess :(

I'd probably recommend just hacking around this by removing the `[workspace]` in the `witx` crate for now?  Ideally we'll fix this in the long term by separating the tooling and the `*.witx` files since we want tooling as a crates.io dep and the `*.witx` files as a submodule.

**Comment by cratelyn** [comment]
```
Run rustc scripts/publish.rs
thread 'main' panicked at 'failed to find "witx-cli" in whitelist or blacklist', scripts/publish.rs:135:13
```

This shouldn't be _too_ hard to fix, but I see some special logic around `witx` and that'll have to wait until tomorrow morning for me.

**Comment by cratelyn** [comment]
Oh I'm going to mark this as "ready for review" since we're kinda already in the process of reviewing this work. :+1:

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
