### PR TITLE
pulley: Initial scaffold of SIMD support 

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fills out some of the initial infrastructure necessary for
supporting the SIMD proposal to WebAssembly in the Pulley interpreter,
namely 128-bit simd. The `VRegVal` union has been filled out with
various types, endianness questions are settled, and initial
implementations of a suite of opcodes are added to get a basic set of
tests working throughout the backend.

cc https://github.com/bytecodealliance/wasmtime/issues/9783

### CODE REVIEW

**Comment by alexcrichton** [comment]
based on https://github.com/bytecodealliance/wasmtime/pull/9819, https://github.com/bytecodealliance/wasmtime/pull/9817 (approved and waiting on CI), and https://github.com/bytecodealliance/wasmtime/pull/9815 (approved and waiting on CI)

**Review by fitzgen — APPROVED** [review]
Very nice

**Comment by alexcrichton** [comment]
@fitzgen if you wouldn't mind taking a look at the second commit here. The CI failure was due to endianness failures on s390x because big-endian loads/stores of vectors aren't implemented in Pulley. I personally find it easiest to sidestep the question entirely, so I've redefined wasm globals to be little-endian instead of big-endian, updated some accessors, and then additionally updated pulley stack loads/stores of vectors to be in little-endian.

I also needed to implement `bitcast` for an s390x test which got a few more wast tests passing.

**Review by fitzgen — APPROVED** [review]
SGTM

**Pull request merged**
