### PR TITLE
Replaces `load_file` with `load_bytes` in rust macro

### PR DESCRIPTION
**Pull request by jpopesculian**
Loading an `AsRef<[u8]>` object is just more flexible than a filestring.
In the end you can just do `std::fs::read(&str)?` as the argument to get
the same behavior, but the reverse is a lot harder.

### CODE REVIEW

**Comment by jpopesculian** [comment]
Of course the samples will also have to be updated....

**Comment by yurydelendik** [comment]
When multiple wasm modules are loaded, just loading bytes without additional metadata is not useful for troubleshooting. It will be nice to have something user friendly associated with module bytes, e.g. a part of file name/URL.

Background: I'm working of producing meaningful trap backtrace at the moment. An optional module name entry can be present in the wasm name section, but it is rarely filled by producers. The `load_files` could provide that user friendly tag. Can `load_bytes` have optional parameter for that?

It is worth to notice that file path may assist with resolving depended modules locations. Do we need to add a resolver object parameter to address that?

**Comment by jpopesculian** [comment]
It seems like then you would like some kind of mofule descriptor struct then?

```rust
struct ModuleDescriptor<R: io::Read, M: ModuleResolver> {
  wasm: R,
  name: String,
  module_resolver: M
}
```

Which you can then build `from_bytes` or `from_file` and then just load it?

**Comment by alexcrichton** [comment]
Thanks for the PR! Could this perhaps leave the existing method in place, but add the new method as well? (and implement them in terms of one another)

**Comment by jpopesculian** [comment]
Hey @alexcrichton, I put `load_file` back into the macro. Let me know what you think!

**Pull request merged**
