### PR TITLE
Retry the entire release process, not just uploading one asset

### PR DESCRIPTION
**Pull request by alexcrichton**
Another attempt to mitigate #978

### CODE REVIEW

**Comment by alexcrichton** [comment]
Releases start out by deleting the previous release so I think we should be good in that regard, but we'll find out soon :)

**Comment by peterhuene** [comment]
I thought that only happens for `dev`?

**Comment by alexcrichton** [comment]
Hm yes indeed... If this works out I'll look into enabling deletion of previous releases too

**Comment by peterhuene** [comment]
Only on retry I assume :)

**Pull request merged**
