### PR TITLE
🌈 cranelift: Provide an `entity_impl!` variation for external handles

### LINKED ISSUE #3047: `entity_impl!` doesn't work when tuples are private
#### Feature

Hi! :wave: I'd like to propose extending [`cranelift_entity::entity_impl`](https://docs.rs/cranelift-entity/0.75.0/cranelift_entity/macro.entity_impl.html) to accept an expression that ought to be used to construct the given entity.

#### Benefit

In certain corner cases, particularly when using libraries that generate code from `.witx` defintions, we want to use `entity_impl!` with handle types that are not defined ourselves. Consequentially, we cannot always construct the handle directly via a statement like `$entity(index as u32)`.

I put together a Rust Playground example demonstrating the problem [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd3cc30e63be51d6b52a2ec12a540c83), you could also refer to [this gist](https://gist.github.com/rust-play/bd3cc30e63be51d6b52a2ec12a540c83).

#### :question: Implementation

This part I have some questions, and welcome advice. At a high level, I hoped for this to look something like this...

```diff
macro_rules! entity_impl {
     ($entity:ident) => { ... };
     ($entity:ident, $display_prefix:expr) => { ... };
+    ($entity:ident, $display_prefix:expr, $construct:expr) => { ... };    
}
```

...which would allow an invocation shaped like:

```rust
entity_impl(ExampleHandle, "example-prefix-", (index as u32).into())
```

However, when experimenting with this, I ended up running into errors shaped like `cannot find value 'index' in this scope`. I tried alternative [designators](https://doc.rust-lang.org/beta/rust-by-example/macros/designators.html) like `stmt`, but didn't have much luck.

I'm happy to carry out the fix for this, but might need a bit of help deciding how to present this change to callers.

### PR DESCRIPTION
**Pull request by cratelyn**
This fixes #3047; building on @cfallin's outline [here](https://github.com/bytecodealliance/wasmtime/issues/3047#issuecomment-871749805).

This branch expands `entity_impl!` so that it can be used in conjunction with handle types that don't expose a tuple constructor e.g. `Type(0)`. This is motivated by use-cases involving `wiggle`, see fastly/Viceroy#16, or the `other_entity` test cases in this diff, for more information!

### CODE REVIEW

**Comment by pchickey** [comment]
The CI issues are a known nightly bug that should be fixed soon

**Comment by cratelyn** [comment]
> The CI issues are a known nightly bug that should be fixed soon

Ah! There's no urgency on my part for this PR, thanks for flagging this. Feel free to revisit whenever that nightly bug has been fixed.

**Review by cfallin — APPROVED** [review]
LGTM, thanks! Happy to merge once the CI issue resolves.

**Comment by bnjbvr** [comment]
(using the old close-then-reopen trick to retrigger CI)

**Comment by bnjbvr** [comment]
Another spurious failure: cargo-deny has found a security issue in one of the dependencies, which should either be ignored or fixed in a different PR (if the dependency already has been updated).

**Comment by cfallin** [comment]
Thanks!

**Pull request merged**
