### PR TITLE
Move wasm data/debuginfo into the ELF compilation image

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit moves existing allocations of `Box<[u8]>` stored separately
from compilation's final ELF image into the ELF image itself. The goal
of this commit is to reduce the amount of data which `bincode` will need
to process in the future. DWARF debugging information and wasm data
segments can be quite large, and they're relatively rarely read, so
there's typically no need to copy them around. Instead by moving them
into the ELF image this opens up the opportunity in the future to
eliminate copies and use data directly as-found in the image itself.

For information accessed possibly-multiple times, such as the wasm data
ranges, the indexes of the data within the ELF image are computed when
a `CompiledModule` is created. These indexes are then used to directly
index into the image without having to root around in the ELF file each
time they're accessed.

One other change located here is that the symbolication context
previously cloned the debug information into it to adhere to the
`'static` lifetime safely, but this isn't actually ever used in
`wasmtime` right now so the unsafety around this has been removed and
instead borrowed data is returned (no more clones, yay!).

cc #3230

### CODE REVIEW

**Comment by alexcrichton** [comment]
Review-wise the first two commits here are https://github.com/bytecodealliance/wasmtime/pull/3231, so only the later commits are part of this PR

**Comment by alexcrichton** [comment]
Ok rebased on `main` now that  #3231 has merged

**Comment by alexcrichton** [comment]
On CI the ubuntu builder (x86_64 linux) failed with

```
failures:

---- wast::Cranelift::misc::bulk_memory_operations::imported_memory_copy_pooling stdout ----
thread 'wast::Cranelift::misc::bulk_memory_operations::imported_memory_copy_pooling' panicked at 'called `Result::unwrap()` on an `Err` value: failed directive on tests/misc_testsuite/bulk-memory-operations/imported-memory-copy.wast:94:1

Caused by:
    0: result 0 didn't match
    1: expected                  1 / 0x0000000000000001
       actual                    0 / 0x0000000000000000', /home/runner/work/wasmtime/wasmtime/target/debug/build/wasmtime-cli-57f1ea6755e2ec03/out/wast_testsuite_tests.rs:333:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1037:23
   4: all::wast::Cranelift::misc::bulk_memory_operations::imported_memory_copy_pooling
             at ./target/debug/build/wasmtime-cli-57f1ea6755e2ec03/out/wast_testsuite_tests.rs:328:17
   5: all::wast::Cranelift::misc::bulk_memory_operations::imported_memory_copy_pooling::{{closure}}
             at ./target/debug/build/wasmtime-cli-57f1ea6755e2ec03/out/wast_testsuite_tests.rs:326:13
   6: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    wast::Cranelift::misc::bulk_memory_operations::imported_memory_copy_pooling

test result: FAILED. 457 passed; 1 failed; 0 ignored; 0 measured; 213 filtered out; finished in 69.78s

error: test failed, to rerun pass '-p wasmtime-cli --test all'
```

I'm going to rerun to see if it's spurious because I can't reproduce locally. If it's spurious, though, that makes this worse...

**Comment by peterhuene** [comment]
That's worrisome and not something I've seen before.

**Comment by peterhuene** [comment]
I can't explain why this would be spurious, but it gives me pause given the fact we just changed memory initialization code a bit (the failure appears to be on just validating that an imported memory has the expected data segment initialized).

**Comment by alexcrichton** [comment]
Yeah I suspect the error is in my previous PR as well, I'll try to dig more into that tomorrow, this shouldn't land in the meantime

**Comment by alexcrichton** [comment]
Ok I've reproduced this locally, more investigation tomorrow!

**Comment by alexcrichton** [comment]
I believe the spurious failure I saw wasn't in this PR, but rather the previous PR, and should be fixed in https://github.com/bytecodealliance/wasmtime/pull/3238, so I'm gonna go ahead and merge this.

**Pull request merged**
