### PR TITLE
Encode modules with variable-length integers

### PR DESCRIPTION
**Pull request by alexcrichton**
Update `Module::{serialize,deserialize}` to use variable-length integers
with `bincode` to make the output artifacts smaller. Locally this
reduces the size of #2318 from 160 to 110 MB, a 30% decrease in size!
Deserialization performance is slightly slower, but seemingly within the
range of noise locally for me.

### CODE REVIEW

**Review by yurydelendik — APPROVED** [review]

**Comment by fitzgen** [comment]
To be clear this is just enabling variable length encoding for integers, right? It is *not* switching to a delta encoding (which would ensure that essentially all addresses are 1-byte encoded) correct?

**Comment by alexcrichton** [comment]
Ah yes indeed, a delta encoding might make it even more further compact.

I've so far shied away from big changes like that though. I think we may want to do it eventually, but it trades-off in-memory footprint for lookup speed since we can no longer quickly do a random lookup for a particular trapping pc. Not that we necessarily need that to be *too* too fast.

**Comment by fitzgen** [comment]
I'm only advocating for delta encoding in the serialized format, not the in-memory representation.

**Comment by tschneidereit** [comment]
> I'm only advocating for delta encoding in the serialized format, not the in-memory representation.

I think it'd be good to try not to have those two deviate too much: ideally we should at some point be able to mmap the on-disk representation entirely or almost entirely instead of having to read and deserialize it.

There clearly are size/speed tradeoffs to be had here, so that might not be the *only* thing we support, but I hope it can become *a* thing we support :)

**Pull request merged**
