### PR TITLE
bench-api: configure execution with a flags string

### PR DESCRIPTION
**Pull request by abrown**
As discussed in a previous Wasmtime meeting, we need a way to be able to configure Wasmtime when running it in the Sightglass benchmark infrastructure. The easiest way to do this seemed to pass a string from Sightglass to the bench-api library and parse this in the same way that Wasmtime parses its CLI flags. The structure that contains these flags is `CommonOptions`, so it has been moved to its own crate to be depended on by both `wasmtime-cli` and `wasmtime-bench-api`. Also, this change adds an externally-visible function for parsing a string into `CommonOptions`, which is used for configuring an engine.

### CODE REVIEW

**Comment by abrown** [comment]
@alexcrichton: haven't touched the publish script yet to add the new `wasmtime-cli-flags` crate but I will do that next if the general approach makes sense.

**Comment by alexcrichton** [comment]
This seems like a reasonable approach to me and I sort of like the pressure to expose all engine options as CLI flags one way or another.

Is it possible for the bench API to be configured with a list of strings though? I'm personally hesitant to bring in dependencies like `shellwords` if we can, but if it makes more sense from the top-level to only have a single string that's probably the way to go.

**Comment by abrown** [comment]
I was being pretty cautious when including `shellwords` but, thinking about it more, there don't seem to be any settings that I can think of that use spaces or that would require quoting. I removed the dependency in f5adfa0 and perhaps we could re-add it in the future if one of us finds the need for escaping within the flags string. I do think it would be easier to keep the flags as a string rather than an array of strings to keep the C interface as simple as possible (but, I could be swayed the other way too, I guess; just mostly worried about how many more pointers one would have to keep correct).

**Comment by abrown** [comment]
The cargo deny error is due to `uuid`:

```
error[B004]: found 2 duplicate entries for crate 'uuid'
    ┌─ /home/abrown/Code/wasmtime/Cargo.lock:190:1
    │  
190 │ ╭ uuid 0.8.2 registry+https://github.com/rust-lang/crates.io-index
191 │ │ uuid 1.0.0 registry+https://github.com/rust-lang/crates.io-index
    │ ╰────────────────────────────────────────────────────────────────^ lock entries
    │  
    = uuid v0.8.2
      └── listenfd v0.3.5
          └── wasmtime-cli v0.37.0
    = uuid v1.0.0
      └── cap-tempfile v0.24.3
          └── (dev) wasi-tokio v0.37.0
              └── wasmtime-wasi v0.37.0
...
```

Apparently `uuid` published its 1.0.0 version two weeks ago and some of the wasmtime crates already depend on it. But `listenfd` doesn't, so I'll add an exception for it.

**Pull request merged**
