### PR TITLE
Add Config::fuel_cost to customize fuel cost func

### PR DESCRIPTION
**Pull request by coolreader18**
Adds `Config::fuel_cost` as described in #5109. I'm not sure where test cases for fuel are, if they exist?

### CODE REVIEW

**Comment by coolreader18** [comment]
Hmm, should I use saturating_add for adding `self.fuel_cost += fuel_cost()`? An overflow there would probably be bad, I assume.

**Comment by pepyakin** [comment]
I wonder how this interacts with the AOT compilation.

Consider that the user creates the engine with a specific fuel cost function, then loads a module, and then serializes it into a file.

Then, perhaps in another version of the program, changes the fuel cost function and loads the previously serialized module. However, the fuel behavior that the loaded module exhibits will be different from the configured fuel costs. I would argue that this is an unexpected behavior. At the very least, I would expect to get an error during the module loading.

To do so, the metadata for the compiled artifact should embed the module costs, but that's not really possible with a closure. 

It seems to me that the costs schedule would better be represented, *conceptually*, by a `BTreeMap<Opcode, u32>`. That way, you could serialize and embed them into the compiled artifact.

**Comment by alexcrichton** [comment]
Thanks for the PR here! Could you expand a bit more on the use case that you're envisioning for this? This is a pretty low-level degree of control to give from an embedding API around fuel and feels like a relatively large addition with the enum addition here (not that there's a better way to model this that I know of). I'm curious though if there's perhaps an alternative solution which doesn't expose such low-level control of the fuel costs, but there may not be.

I would also be slightly concerned about the AOT-story here since in theory the costs all need to be equivalent, but that can also be "patched" by returning an error and disabling serialization if this `Config` field is configured.

**Comment by coolreader18** [comment]
Oh, I missed that `Module::deserialize` checks that the engine configs are the same; those are good points about AOT. Maybe `fuel_cost()` could take a data structure like rust-unic's [`CharDataTable`](https://docs.rs/unic-char-property/0.9.0/unic_char_property/tables/enum.CharDataTable.html) or something.

In any case, the motivating use case was switching an existing runtime from wasmer, which has cost customization by default as part of its metering instrumentation and so we were utilizing that. I suppose it is worth looking into how valuable that actually is, when obviously the wasm doesn't map one-to-one to machine code anyway...

**Comment by coolreader18** [comment]
That makes sense, I'll look at sketching out a simpler (configuration-wise) solution to this or probably just reworking fuel usage in our codebase. Thank you for your help!

**Comment by jameysharp** [comment]
In case you haven't already seen it, I'll mention that Wasmtime's "[epoch interruption](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.epoch_interruption)" may be a good alternative to fuel, depending on what you're using it for. From the documentation:

> In general, epoch-based interruption results in faster execution. This difference is sometimes significant: in some measurements, up to 2-3x. This is because epoch-based interruption does less work: it only watches for a global rarely-changing counter to increment, rather than keeping a local frequently-changing counter and comparing it to a deadline.
>
> Fuel, in contrast, should be used when deterministic yielding or trapping is needed. For example, if it is required that the same function call with the same starting state will always either complete or trap with an out-of-fuel error, deterministically, then fuel with a fixed bound should be used.

**Pull request closed without merging**
