### PR TITLE
cranelift-codegen: depend on an exact version of `isle`

### PR DESCRIPTION
**Pull request by fitzgen**
This should (hopefully) fix our publish script: https://github.com/bytecodealliance/wasmtime/runs/4419646007?check_suite_focus=true

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
LGTM!

I wonder if we're also going to have an issue with using the `isle` crate name (in Cargo.toml [here](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/isle/isle/Cargo.toml)) rather than `cranelift-isle`, since (as you discovered) it's reserved right now? Should we update that in this PR as well?

**Comment by fitzgen** [comment]
> I wonder if we're also going to have an issue with using the `isle` crate name (in Cargo.toml [here](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/isle/isle/Cargo.toml)) rather than `cranelift-isle`, since (as you discovered) it's reserved right now? Should we update that in this PR as well?

I don't think this is an issue, as we had `peepmatic` and not `cranelift-peepmatic` and everything worked.

**Comment by cfallin** [comment]
> > I wonder if we're also going to have an issue with using the `isle` crate name (in Cargo.toml [here](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/isle/isle/Cargo.toml)) rather than `cranelift-isle`, since (as you discovered) it's reserved right now? Should we update that in this PR as well?
> 
> I don't think this is an issue, as we had `peepmatic` and not `cranelift-peepmatic` and everything worked.

Is the crate not published, then? I guess I don't fully understand exactly how we determine which crates are published; if dev-dependencies don't go to crates.io then indeed, everything should just work, and nevermind me!

**Comment by fitzgen** [comment]
Ah no, this is me failing my reading comprehension. The `isle` crate name is already taken on crates.io, and this is what I was failing to understand.

**Comment by fitzgen** [comment]
So yeah, I think `cranelift-isle` is the way to go.

**Comment by fitzgen** [comment]
The rename to `cranelift-isle` is done now.

**Review by cfallin — APPROVED** [review]
:+1:

**Pull request merged**
