### PR TITLE
Capture a backtrace before calling wasm

### PR DESCRIPTION
**Pull request by alexcrichton**
This helps mitigate the issue, at least locally, described in #829 and
there's some more comments inline in the code as well.

### CODE REVIEW

**Comment by sunfishcode** [comment]
I'm not familiar with the `backtrace` crate; would it be difficult to have the single handler just collect the raw addresses on the stack, and then spawn a new thread to do the symbolication and reporting?

This may not seem safe to do from within a signal handler, but we know that if `CheckIfTrapAtAddress` returns true, the trap happened within wasm code at a known trap location (eg. a heap load or store), so we don't have to worry about `malloc` being in an inconsistent state or other things that can be dangerous from within signal handlers in other contexts.

**Comment by alexcrichton** [comment]
That's roughly what's already happening actually. While there's a bit more going on it's pretty minor, currently the fault stems from calling `_Unwind_Backtrace` which is *the* way to get addresses to get symbolicated later. The only other alternative would be to have another thread backtrace the first thread, but that can get much more tricky...

**Comment by alexcrichton** [comment]
@sunfishcode I've opted to place this in the one-time initialization with signals and everything else, which I'm hoping is a bit more lightweight of a location to put it.

**Comment by sunfishcode** [comment]
FWIW, I did some quick experiments and confirmed that the overhead of this change is in the noise.

**Pull request merged**
