### PR TITLE
Call verifier after egraph pass

### LINKED ISSUE #6855: cranelift: Run verifier after optimizations during testing
👋 Hey

#### Feature

We should run the verifier after all of the optimization passes during testing, or when running via `clif-util`.

#### Benefit

This would really improve the error messages for egraphs optimization authors.

Here's a recent example: https://github.com/bytecodealliance/wasmtime/pull/6851#issuecomment-1682067457 these error messages are provided by the backends, but that really confuses things since what is really happening is that we are producing invalid CLIF in the mid end.

Both of those examples would have really neat error messages if they were produced by the verifier.

#### Implementation

We probably don't want to enable this by default since it will slow down the compilation pipeline.

On of my ideas on how to implement this would be to add a new flag (i.e. `run_verifier_after_opts`) that would be disabled by default but we could enable in `clif-util` and in our test runner.

I don't know if we already have a `do_extra_checks` flag, but we can also maybe use that one. Or we could maybe even use `enable_verifier` itself.

#### Alternatives

Running this in the fuzzer is also an option but I think the costs might outweigh the benefits. I'm not sure.

We can also not do this, and write down somewhere that it's a good idea to recompile the optimized code manually. I have previously started doing that after encountering weird issues, and this time it worked out.

### PR DESCRIPTION
**Pull request by gurry**
Fixes #6855

### CODE REVIEW

**Review by afonso360 — APPROVED** [review]
This looks pretty much like what I expected. Thanks!

**Comment by gurry** [comment]
I wonder what tests we can write for this since any faulty input will be caught much before we reach the egraph pass by the earlier verifier invocations.

**Comment by afonso360** [comment]
Huh, I'm not sure how we would test this. Maybe @jameysharp has an idea?

**Comment by jameysharp** [comment]
Yeah, I don't think we can write sensible tests for running the verifier after specific passes. It wouldn't be too hard to add an invalid egraph rule that only matches when some flag is set, and only turn that flag on in a test, but I don't think it's worth doing that.

Mostly I think we'll notice whether this is working whenever we write new incorrect egraph rules, which I'm sure will happen often enough. :sweat_smile:

**Comment by gurry** [comment]
That makes sense @jameysharp. Thanks.

**Pull request merged**
