### PR TITLE
cranelift: Update regalloc2

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

This PR updates regalloc2 to the latest version, which adds a new RegClass. All backends currently do not make use of this third RegClass.

This might also need a cargo vet update.

### CODE REVIEW

**Comment by jameysharp** [comment]
I think we might want a wildcard-audit for regalloc2 but I'm not sure what criteria @alexcrichton used for picking initial wildcard audits.

I'd also like to check with @elliottt and @cfallin about whether they have any concerns about the state of this RA2 release.

**Comment by alexcrichton** [comment]
Oh no criteria, I mostly got tired of recertifying all the publishes! I think though a good criteria is "if your audit will be rubber-stamped may as well make it a wildcard audit". Or in other words for crates that we ourselves are authoring and publishing I think it's reasonable to have wildcard audits.

**Comment by cfallin** [comment]
> I'd also like to check with @elliottt and @cfallin about whether they have any concerns about the state of this RA2 release.

No concerns on my end at least -- @elliottt already upgraded us to 0.7.0 which was the bigger diff (no more special handling of program moves) and so this one should have no impact at all other than the stated one (new register class!).

**Review by elliottt — APPROVED** [review]
This looks great! Thanks for plumbing through the changes, and also for moving the regalloc dep to the workspace Cargo.toml!

**Pull request merged**
