### PR TITLE
Merge the Cranelift repository into Wasmtime

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is intended to be the final merge point and implementation of https://github.com/bytecodealliance/cranelift/issues/1408. The current plan is to merge this later this afternoon, and I'll be updating this as necessary if any other cranelift PRs get merged.

Discussion is happening [on Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/217117-cranelift/topic/merge.20repo.20with.20wasmtime) currently. I'm mostly posting this to start kicking the tires on CI.

If anyone is curious for review, here's the highlights:

* Cranelift's history was rewritten as-if it were all entirely written in a `cranelift/` folder. Additionally folders named `cranelift-foo` are now simply named `cranelift/foo`. This rewrite is based on https://github.com/bytecodealliance/cranelift/commit/fe3990375d7073b49af90628625324308b8c0a64.
* A git merge commit was created with the current wasmtime master (121bbd36568c506a39b2dd97a95dd2b963960eb7) and the rewritten master branch.
* Following the git merge I added a bunch of commits to clean up various files, documentation, integration, etc. These follow-up commits are probably the best ones to review.

### CODE REVIEW

**Comment by bjorn3** [comment]
1. A lot of commits are missing.
2. Why rewriting history instead of moving as a separate commit? That would make it much easier to move PR's to this repo.

**Comment by alexcrichton** [comment]
@bjorn3 hm can you give more information? A comment like "A lot of commits are missing" isn't really all that helpful. I don't really know what you mean by this, and I don't think any commits are missing, so in an attempt to bridge the two understandings I'm going to need more information.

As for your second point this has been previously discussed. The purpose of preserving history of some kind is so `git blame` works. Additionally I do not understand what you mean by it would be much easier to move PRs. Again, more information is needed to help bridge the understandings. I've [created a script and directions](https://gist.github.com/alexcrichton/8cb3f4ef7c25317ba6824ee31e3e53aa) of how to move PRs which I've tested out, for example on the ARM64 backend, and subjectively find it quite easy to work with.

**Comment by bjorn3** [comment]
> A comment like "A lot of commits are missing" isn't really all that helpful. I don't really know what you mean by this, and I don't think any commits are missing, so in an attempt to bridge the two understandings I'm going to need more information.

In mobile mode gh show the first commit as being 5 months ago. Switching to desktop mode, it says that only the newest 250 commits are shown, so that means no commits were actually missing.

> Additionally I do not understand what you mean by it would be much easier to move PRs.

I believe `git rebase` handles moved files fine, so moving the files as a separate commit would make updating to this repo a rebase away.

> The purpose of preserving history of some kind is so git blame works.

According to the `git blame` man page:

> The origin of lines is automatically followed across whole-file renames

**Comment by alexcrichton** [comment]
@bjorn3 yes most git commands handle renames well, but commands like `git log` do not, by default, show history across file renames. They only show history up to the rename. It was decided, then that it's be better to rewrite history because no one had a strong preference to specifically preserve the existing git history.

**Pull request merged**
