### PR TITLE
cranelift: Remove `is_pic` predicate from x86 backend

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

This PR removes the `is_pic` predicate from the x86 backend. It isn't used anywhere as a predicate form. We always use the shared flags setting.

It also has a negated form, which was the only remaining use of `PredicateNode::Not`.

### CODE REVIEW

**Review by jameysharp — APPROVED** [review]
I was wondering about that TODO comment recently but didn't investigate it. Thank you for cleaning this up!

**Review by abrown — COMMENTED** [review]
I believe there is another use of `PredicateNode::Not` over in `cranelift/codegen/meta/src/cdsl/mod.rs`? I'm fine with this otherwise.

**Comment by abrown** [comment]
...it's also a bit worrying that the CI didn't pick that up?!

**Comment by jameysharp** [comment]
I was worried about CI for a moment after seeing your comment too. But both remaining uses of `PredicateNode::Not` are in a macro, in branches which were only used by the now-deleted `predicate!(!is_pic)`. Since that macro is never expanded with input matching those cases, the compiler didn't see anything wrong.

We should delete both `!$a:ident` cases from `macro_rules! predicate` now, but fortunately the only harm in leaving them there is confusion during maintenance later.

**Comment by abrown** [comment]
Ah, good!

**Pull request merged**
