### PR TITLE
Release Wasmtime 1.0.1

### PR DESCRIPTION
**Pull request by wasmtime-publish**
This is an [automated pull request][process] from CI to create a patch
release for Wasmtime 1.0.1, requested by @cfallin.

It's recommended that maintainers double-check that [RELEASES.md]
is up-to-date and that there are no known issues before merging this
PR. When this PR is merged a release tag will automatically be
created, crates will be published, and CI artifacts will be produced.

[RELEASES.md]: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md
[process]: https://docs.wasmtime.dev/contributing-release-process.html

### CODE REVIEW

**Comment by cfallin** [comment]
Updated RELEASES file. Waiting for a bit to see if any other fixes need to ride along with this patch release, otherwise we'll merge later today.

**Review by cfallin — APPROVED** [review]

**Review by alexcrichton — APPROVED** [review]

**Comment by bjorn3** [comment]
No other patches necessary for cg_clif. All tests passed on AArch64 when I was working on my PR. They already passed on x86_64 (both Linux and macOS) @afonso360 said they found some regression on Windows, but that wasn't working great before Cranelift 0.88 anyway (or at all in case of MSVC, no idea if the regressions also affect MinGW. @afonso360?), so I don't mind having to wait another release personally.

**Comment by afonso360** [comment]
The actual regressions were with build system stuff on cg_clif so I think we are good here. But we also have some tests failing on [MinGW](https://github.com/afonso360/rustc_codegen_cranelift/actions/runs/3127842401/jobs/5074940188#step:7:558) with windows as a host, which I think was working before but I'm not quite sure so it might not be a regression.

**Comment by cfallin** [comment]
Alright, after checking with folks, there's nothing else that we want to include here so I'll go ahead and merge with just this cherrypick. Thanks again for the fix!

**Pull request merged**
