### PR TITLE
x86_32: legalize br{z,nz}.i64

### PR DESCRIPTION
**Pull request by whitequark**

### CODE REVIEW

**Comment by whitequark** [comment]
cc @iximeow

**Comment by whitequark** [comment]
No logs for failed builds?..

**Comment by tschneidereit** [comment]
> No logs for failed builds?..

Yeah, something's wrong here. I just retriggered the tests in the hope that this was an intermittent infra issue.

**Comment by whitequark** [comment]
> I just retriggered the tests in the hope that this was an intermittent infra issue.

I think that broke again, though less severely.

**Comment by iximeow** [comment]
I tried rerunning again (because why not) only to see the same mac builds fail. Still no logs or indication of how to acquire them..

**Comment by tschneidereit** [comment]
Just tried again, because indeed: why not, but no change. Given that
- the failures are all on macOS, yet this PR doesn't do anything macOS specific
- the failures happen well before anything this PR changes comes into play
- we've since had multiple successful runs in other PRs
I wonder if something's just borked about this PR.

@whitequark would you be up for opening a fresh PR for these changes? 🤞that makes it go away.

**Comment by whitequark** [comment]
@tschneidereit https://github.com/bytecodealliance/wasmtime/pull/1794

**Comment by tschneidereit** [comment]
@whitequark thank you! Given that #1794 worked, would it make sense to close this and open a new PR with identical patches? It seems implausible that the difference in code chances between this PR and #1794 would translate into this difference in CI success.

**Comment by whitequark** [comment]
> Given that #1794 worked, would it make sense to close this and open a new PR with identical patches? It seems implausible that the difference in code chances between this PR and #1794 would translate into this difference in CI success.

Er, sorry, I actually made a mistake here--I pushed a wrong branch. Let me do the right thing...

**Comment by whitequark** [comment]
https://github.com/bytecodealliance/wasmtime/pull/1795

**Pull request closed without merging**
