### PR TITLE
Support declaring anonymous functions and data objects

### LINKED ISSUE #2220: Add define_anonymous_data function to cranelift-module
#### Feature

Add a method to cranelift-module that defines a data object without creating a new symbol.

#### Benefit

Avoiding symbols for anonymous data objects improves linker times.

#### Implementation

For `cranelift-simplejit` symbol names are unused for everything except for imports and exports already. For `cranelift-object` the data object could be added to the right section and then the section id and offset could be stored to generate the right relocations in the future.

#### Alternatives

Using `Linkage::Local` requires you to generate an unique name and has a negative impact on compilation times.

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #2220

### CODE REVIEW

**Comment by bjorn3** [comment]
@pchickey Could you please review this PR?

**Review by cfallin — COMMENTED** [review]
This looks reasonable to me overall; the API changes are relatively minor. Thanks!

It seems a little weird to rely on symbol naming to communicate to the linker to elide certain symbols from the function table; I guess there isn't a better out-of-band way (symbol type, etc) to ensure this happens?

Happy to merge if we're satisfied there's not a better way re: above!

**Comment by bjorn3** [comment]
Not that I know of. Using `.L` as prefix is the standard way to indicate labels. Even LLVM uses symbol names like `.L__unnamed_1`.

**Comment by cfallin** [comment]
Sounds good, then; thanks for looking into it!

**Pull request merged**
