### PR TITLE
Add s390x build workflow

### PR DESCRIPTION
**Pull request by uweigand**

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
Thanks!

**Comment by uweigand** [comment]
@cfallin Looks like the build job succeeded.   I can't check the generated binaries since it looks like the actual upload step is skipped for a PR run.

**Comment by alexcrichton** [comment]
Oh actually if you go to the [build page](https://github.com/bytecodealliance/wasmtime/actions/runs/1254374336) the artifacts are at the bottom, and [individual runs](https://github.com/bytecodealliance/wasmtime/pull/3375/checks?check_run_id=3654149979) also have a drop-down for artifacts. Mind double-checking those to confirm they work?

**Comment by uweigand** [comment]
> Oh actually if you go to the [build page](https://github.com/bytecodealliance/wasmtime/actions/runs/1254374336) the artifacts are at the bottom, and [individual runs](https://github.com/bytecodealliance/wasmtime/pull/3375/checks?check_run_id=3654149979) also have a drop-down for artifacts. Mind double-checking those to confirm they work?

Ah, I see!   I've just done a few quick tests (running the wasmtime on a few test files), but everything looks good to me so far.

**Pull request merged**
