### PR TITLE
Update cap-std dependency to 0.13.9

### PR DESCRIPTION
**Pull request by uweigand**
This fixes a build failure on s390x.

### CODE REVIEW

**Comment by abrown** [comment]
Does anyone know the exact reason why we are seeing [these CI errors](https://github.com/bytecodealliance/wasmtime/pull/2829/checks?check_run_id=2332860293#step:15:6400) now? We ran across something similar and assumed it was because of something new in Rust 1.51?

**Review by abrown — APPROVED** [review]
Besides the CI errors, this looks fine to me!

**Comment by uweigand** [comment]
Looks like just re-running CI made the failures go away.  Can this be merged now?

**Comment by sunfishcode** [comment]
Merging!

**Pull request merged**
