### PR TITLE
Fix compilation for armv7

### PR DESCRIPTION
**Pull request by pepyakin**
Provide a dummy symbol for `PROBESTACK` to make wasmtime compile on armv7.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Have you confirmed this works though? I don't think `target_arch = "armv7"` will ever match (I believe it's always `"arm"`)  and additionally I don't think you can cast a raw pointer to a function pointer?

**Comment by pepyakin** [comment]
I run a test build on armv7 and it worked from the first time! I should've been alarmed.

**Comment by pepyakin** [comment]
Turned out that there are no `__register_frame` and `__unregister_frame`, so guarded [them as well](https://github.com/bytecodealliance/wasmtime/pull/943/commits/566e954532f16bffedeb35b4dee1e1c1535c757f#diff-e6d6591c311babb3788fd238d0c29d41R4).

**Comment by alexcrichton** [comment]
Hm I'm not sure how to best handle this, it looks like the goal is to get *something* compiling on armv7 rather than something working compiling on armv7. I'm not sure how we're going to know, though, how to come back and fix these locations later, since they're pretty critical for functionality?

**Comment by pepyakin** [comment]
@alexcrichton yeah precisely! I do not expect it working for armv7 since cranelift and lightbeam do not support armv7 and there are no other upcoming backends on the horizon. I also think that because these locations are so critical that somebody who adds these platforms to wasmtime will have to provide proper implementations - otherwise, you won't be able to run anything unless you fix those.

**Comment by alexcrichton** [comment]
That's true, yeah, but I'm curious what the purpose is also in getting armv7 to compile? I figured it'd be better to leave these as glaring holes as "someone please implement this" as opposed to letting the eventual future-implementor hit failing tests and try to track these down.

**Comment by pepyakin** [comment]
Ah, OK. There were a minor reasons for our projects (a user of wasmtime) to include this and I figured that this would actually help the future implementor more than linking errors. I am not married to this so feel free to close.

**Comment by alexcrichton** [comment]
I'm personally ambivalent, but would slightly lean towards a preference of not patching up armv7 support like this just yet. I'm curious if others have different opinions though!

**Comment by tschneidereit** [comment]
@pepyakin, can you say a bit more about your use case? I think that'd help to understand the trade-offs a bit better

**Comment by pepyakin** [comment]
Wasmtime not strictly required (we use wasmi as fallback), but we would like to have our users to only make `cargo build --release`. Ideally, cargo would support disabling some features depending on the target platform but it doesn't AFAIK.

I do understand that this is a bit silly : ) Just thought that this would make a little bit better our users' experience and also, as I already mentioned, I assumed that this would actually help the future implementers. That's why I don't feel strongly either way

**Comment by tschneidereit** [comment]
Thank you for the explanation! I see how this is a helpful, if somewhat unfortunate workaround. @alexcrichton, can you think of a better way to handle this? If not, I'd be inclined to say we should take a patch here, and should look into what the exact requirements should be.

**Comment by alexcrichton** [comment]
An alternative would be to use platform-specific dependencies in consumers, but it's generally not a great experience to do that. If we want to take as a feature that we at least compile for other platforms although return errors because things don't work, I'm also ok with that. (it's just a slight lean after all!)

If we do land this I would prefer to fail "loudly" if we can if this code is attempted to be used though. For example instead of `unreachable_unchecked` could we panic when we try to get the address of `__probestack` in the first place? (e.g. during application of relocations)

**Comment by pepyakin** [comment]
Sorry, had no time to finish it and meanwhile it was fixed on our side

**Pull request closed without merging**
