### PR TITLE
Remove HostRef from API

### PR DESCRIPTION
**Pull request by cedric-h**
Unfinished prototyping and attempting to implement #682.

I've decided to start with Module as a testing ground for figuring out how we can begin to hide Hostref from the users. Once we have something we're happy with for Module it should be relatively simple to follow suit for the rest of the API until we can eventually make HostRef private.

How Module relays back information from the ModuleInner it contains is kind of gross; I'm not sure whether we'd want to come up with some clever Deref implementation or some sort of macro or what.

To the best of my knowledge, I believe this is a complete list of everything that needs to be done to make HostRef private.
If there's anything I'm missing, please let me know.

Structs which need to become HostRef wrappers around their Inner counterparts:
- [X] Module
- [ ] Instance
- [x] Store
- [ ] Engine
- [ ] Func
- [ ] Global
- [ ] Table
- [ ] Memory
- [ ] Trap

Misc.
- [ ] HostObject trait for allowing configuration of HostRefs contained in wrapper structs

### CODE REVIEW

**Comment by yurydelendik** [comment]
> we can eventually make HostRef private.

The `set_host_info` and `ptr_eq` needs to stay public. I was suggesting convert `HostRef` into a trait in the #682 and that might solve this. (Add `HostObjRef` trait for now?)

> How Module relays back information from the ModuleInner it contains is kind of gross... we'd want to come up with some clever Deref implementation or some sort of macro or what

That is the price we have to pay for using `Rc<RefCell<T>>`. Using `Ref<T>` keep lifetimes in order and familiar to Rust developers, also have Deref capabilities.

(I think `Clone` near `Module` was a mistake, we have to keep `ModuleInner` as non-clonable)

**Comment by yurydelendik** [comment]
(assuming this PR is WIP) can we have list of items to be done to track status?
e.g.:
- [ ] Add trait for `set_host_info`
- [ ] Convert `Instance`

**Comment by cedric-h** [comment]
Indeed, this PR is a huge WIP.

I'll edit such a list into the post up at the top.

**Comment by alexcrichton** [comment]
Thanks for posting this @cedric-h! I think we'll probably want to tackle this relatively incrementally, starting perhaps from the top-down with `Store` first and finally working our way down to `Instance` and then all the types like `Func` and such. What do you think of that strategy?

**Comment by cedric-h** [comment]
Indeed!
Starting with Module was probably misguided, but now that Module's out of the way I've moved on to Store. Next time I have time I'll tackle Instance.

I went ahead and added a `stores` getter method on Module so that `#[allow(dead_code)]` wasn't needed because of how stores was actually only being used by the `Clone` derive.

**Comment by yurydelendik** [comment]
@cedric-h I wonder if you have a bandwidth to work on this PR. We would like to prioritize this task. Do you have blockers or findings related to this work?

**Comment by cedric-h** [comment]
This can be closed; @alexcrichton has already repeated most of the work here in #771 only based off of a much more recent master than this PR.

**Pull request closed without merging**
