### PR TITLE
cranelift-isle: Do fewer term lookups

### PR DESCRIPTION
**Pull request by jameysharp**
While checking the call graph of extractors during semantic validation, save `TermId` instead of `Sym`. The types are both just integer indexes, but the `TermId` is more useful here. Saving it avoids needing to check for failed map lookups twice, which simplifies the implementation.

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Worth running the ISLE fuzzer for a little while on this change, as the maybe-we-don't-have-that-entity logic is kinda subtle and I've historically found tons of bugs in our keep-going-for-error-reporting stuff this way.

**Comment by jameysharp** [comment]
Ooh, I didn't know there's an ISLE fuzzer! It found an unrelated existing bug pretty quickly. I'll fiddle with it for a while before merging this.

**Comment by fitzgen** [comment]
Yeah it is good to run when hacking on ISLE but isn't something we really want to dedicate oss-fuzz resources towards because our ISLE inputs aren't actually untrusted.

**Comment by jameysharp** [comment]
This PR passed a billion fuzz executions, after an unrelated fix I'll open another PR for.

**Pull request merged**
