### PR TITLE
Add some more audits for my own crates

### PR DESCRIPTION
**Pull request by fitzgen**
Mostly stuff that Firefox is using and asked me to publish audits for, but a couple are in our dep tree as well.

### CODE REVIEW

**Comment by fitzgen** [comment]
cc @bholley

**Review by jameysharp — COMMENTED** [review]
Looks like "arbitrary" is consistently typo'd, which I assume is why there aren't corresponding exemptions being removed. Perhaps a problem for peeking_take_while as well?

**Comment by fitzgen** [comment]
Good catch, thanks.

We don't use `peeking_take_while` in Wasmtime so we don't have an exemption for it to remove.

I think maybe the reason that the `arbitrary` exemptions aren't being remove is that I audited the latest version but we use an older version in `Cargo.lock`?

**Comment by fitzgen** [comment]
> I think maybe the reason that the `arbitrary` exemptions aren't being remove is that I audited the latest version but we use an older version in `Cargo.lock`?

Yeah, I added audits for the earlier versions and the exemptions go away now.

**Review by jameysharp — APPROVED** [review]
Yeah, I think that would explain it. It might be nice to add audits for the versions we're currently using as well, but seems okay without too.

**Comment by fitzgen** [comment]
Yep, done.

**Comment by bholley** [comment]
Thanks!

> I think maybe the reason that the arbitrary exemptions aren't being remove is that I audited the latest version but we use an older version in Cargo.lock?

My general recommendation for this situation (which we've run into as well) is to add an audit both for the latest version as well as the older version in tree.

And yes this PR should cover the ones Firefox is using, though while you're at it you might consider some of the other crates you own that have [download stats in the millions](https://crates.io/users/fitzgen?sort=downloads).

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
