### PR TITLE
cranelift: Remove `copy` instruction

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

This it turned up when looking at list of missing instructions for the fuzzer. `copy` seems to not be used anymore, wasmtime  does not use it, cg_clif  does not use it, and the only use of it in the repository is in tests.

The  docs for this instruction state:
> this instruction is useful for representing intermediate stages during instruction transformations, and the register allocator needs a way of representing register copies.

But it seems that both of those are no longer true, right?

### CODE REVIEW

**Comment by bjorn3** [comment]
It may be useful in the future for handling value debuginfo to denote the start of the lifetime of a variable.

**Comment by fitzgen** [comment]
> It may be useful in the future for handling value debuginfo to denote the start of the lifetime of a variable.

I'd rather remove it for now and if we have some use case for something like debug info lifetimes we can make a purpose-built solution for that rather than trying to fit it into the shape of something that is vestigial and designed for a completely different purpose.

**Comment by fitzgen** [comment]
> But it seems that both of those are no longer true, right?

That's correct. This instruction is from two regallocs ago, sigh.

**Review by fitzgen — APPROVED** [review]
Thanks!!

**Review by jameysharp — APPROVED** [review]
I was already pretty convinced this was a good idea. Then I saw that x64 just panics if asked to lower this opcode, so we clearly don't need it in this form. As Nick said, we can add an instruction like this back later if we find something we need it for.

**Pull request merged**
