### PR TITLE
Update to the latest spec_testsuite and dependencies.

### PR DESCRIPTION
**Pull request by sunfishcode**
Update to target-lexicon 0.10, cranelift 0.54, wast 0.6, faerie 0.14,
and the latest spec_testsuite.

For wast and cranelift-wasm, update the code for API changes.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh heh  the wast update is also happening in https://github.com/bytecodealliance/wasmtime/pull/802! I'll take a look at this as well

**Comment by sunfishcode** [comment]
Oops, sorry for duplicating work here!

Also, I mangled a conflict resolution here; I'll fix that.

**Comment by sunfishcode** [comment]
Ok, the merge conflict is sorted now.

**Comment by abrown** [comment]
No worries; I think this does more than #802 so I'll close that one.

**Comment by sunfishcode** [comment]
I like the way @abrown's #802 factored out the code for f32, f64, and v128 matching into separate functions rather than duplicating the logic for scalar and vector, so I've now incorporated that idea into this PR.

**Pull request merged**
