### PR TITLE
 Speed up a "big stack" test, and test Winch 

### PR DESCRIPTION
**Pull request by alexcrichton**
This test currently takes 50s locally in debug mode locally so optimize
it by disabling optimizations in Cranelift and additionally using the
single-pass register allocator. This drops the test time to ~3s locally.

### CODE REVIEW

**Review by pchickey — APPROVED** [review]
Just to help me understand: does this mean we lose test coverage for cranelift? if we're not losing coverage, why does this test exist?

**Comment by alexcrichton** [comment]
A good question! I did a bit more digging and I've now changed this to:

* This is tested on both Winch and Cranelift now.
* Cranelift disables egraph optimizations
* Cranelift uses the single-pass register allocation pass

That makes the test much speedier now so it will continue to test Cranelift.

**Comment by pchickey** [comment]
Thanks. Comment needs a fix, then its good to go

**Comment by alexcrichton** [comment]
oops, thanks!

**Pull request merged**
