### PR TITLE
riscv64: Further optimize constants loading

### PR DESCRIPTION
**Pull request by a1phyr**
Follow-up of #7131

In some cases we can avoid an `addi` by using `lui` and shifting less

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Thanks for this! Would you be up for updating the rule added in https://github.com/bytecodealliance/wasmtime/pull/7131 as well to match this rule in terms of consistency? I tried to put everything in ISLE in that PR but I like how this PR turned out as well so that may not have been the best option.

I was initially quite perplexed as I thought that this should have already been handled by https://github.com/bytecodealliance/wasmtime/pull/7131 and the "aha!" moment was realizing that there has to be at least 12 trailing zeros since the immediate starts at higher bits. I think being able to see that difference in ISLE might be kind of nice.

No worries either way though, this is a nice improvement, so thanks!

**Review by alexcrichton — APPROVED** [review]
Thanks!

**Comment by a1phyr** [comment]
Do you have a idea of what causes the failure ? I don't understand why the sign bit is set in these tests.

A simple function loading the constant outputs the right code:

```
function %f() -> f64 {
block0:
  v0 = f64const 0xf64.0
  return v0
}

; VCode:
; block0:
;   lui a0,-518695
;   slli a2,a0,31
;   fmv.d.x fa0,a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0x815d9
;   slli a2, a0, 0x1f
;   fmv.d.x fa0, a2
;   ret
```

**Comment by afonso360** [comment]
I think this might be because `lui` for RISC-V 64bit sign extends the immediate after placing it in the register. 

This is the expression that `lui` computes:
```
x[rd] = sext(immediate[31:12] << 12)
```

The immediate has the MSB set, and since we don't fully shift immediate all the way to the top we are observing the sign extension.

**Comment by a1phyr** [comment]
Oh I missed that ! Thanks a lot !

**Comment by a1phyr** [comment]
Note: this does not work for constants like `0xf7fff00000000000` but that would significantly complicate the code.

**Pull request merged**
