### PR TITLE
Bump to Wasmtime v0.29.0 and Cranelift 0.76.0.

### PR DESCRIPTION
**Pull request by cfallin**
Release Wasmtime v0.29.0 and Cranelift v0.76.0.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
r=me, but as you mentioned on Zulip let's wait to hear from @jlb6740. If simd might be done by the end of the week I think it might make sense to squeeze that in before the release

**Comment by alexcrichton** [comment]
Also, while here, I went ahead and updated the release notes -- https://github.com/bytecodealliance/wasmtime/commit/e9fe64f0c7eb14975f1788a57b097258ad8850d0 -- mind including that here?

**Comment by cfallin** [comment]
Ah, I hadn't done that yet, thanks!

**Comment by jlb6740** [comment]
Hi @cfallin @alexcrichton .. Yes there are two more pull requests that are needed to complete SIMD. Specifically what is left is what covers these tests:

```
    match (testsuite, testname) {
        ("simd", "simd_i16x8_extadd_pairwise_i8x16") => return true,
        ("simd", "simd_i32x4_extadd_pairwise_i16x8") => return true,
        ("simd", "simd_int_to_int_extend") => return true,
        ("simd", _) => return false,
        _ => {}
    }
```
The first two are taken care of by pr #3031. It actually works fine but I think we want to do a little refactoring. The lowerings that cover int_to_int_extend I haven't pushed a pr for but have started. Let me see how far I get and give an updated estimate later this week if no urgency to finish by this week.

**Comment by cfallin** [comment]
I just updated this PR to rebase on top of latest `main` with the last x64 SIMD bits (and Alex's just-merged 64-bit memory limit PR). Also updated release notes accordingly. PTAL @alexcrichton for updated note on the latter especially -- thanks!

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
