### PR TITLE
feat: rely on `tracing-subscriber` in tests

### PR DESCRIPTION
**Pull request by rvolosatovs**
`tracing` crate is already used within the codebase, this change allows developers to benefit from that functionality when running and debugging tests

### CODE REVIEW

**Comment by abrown** [comment]
I would still like the ability to log to the console when troubleshooting tests. Does this remove the ability to do that?

**Comment by rvolosatovs** [comment]
> I would still like the ability to log to the console when troubleshooting tests. Does this remove the ability to do that?

No, this mostly concerns the formatting and being able to benefit from additional context added by e.g. https://docs.rs/tracing/latest/tracing/attr.instrument.html

All the usual debugging macros (`debug!`, `info!`, etc..) should still work as usual

`RUST_LOG` value was also correctly handled when I used this to debug #4947

**Comment by alexcrichton** [comment]
The failure in CI is due to the need to have a `cargo vet` listed for this crate. Ideally though we're trying to not pick up new dependencies without vetting them, so to pull this in I think we'll need someone trusted to perform a vet of this crate in its entirety, which may not be a trivial task.

**Comment by rvolosatovs** [comment]
> The failure in CI is due to the need to have a `cargo vet` listed for this crate. Ideally though we're trying to not pick up new dependencies without vetting them, so to pull this in I think we'll need someone trusted to perform a vet of this crate in its entirety, which may not be a trivial task.

I've updated the PR to not modify `Cargo.lock` and instead import the crate the exact same way as already done in https://github.com/bytecodealliance/wasmtime/blob/5a288c2c4029084ab4f44e60481dee1d10d625d2/crates/wiggle/test-helpers/Cargo.toml#L21

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
