### PR TITLE
cranelift: Added fp and, or, xor, not ops to interpreter.

### PR DESCRIPTION
**Pull request by ArtBlnd**
https://github.com/bytecodealliance/wasmtime/pull/4920
@afonso360

### CODE REVIEW

**Comment by ArtBlnd** [comment]
Also, again. sorry for being very late. I think I can use more time this week.

**Review by afonso360 — APPROVED** [review]
>Also, again. sorry for being very late. I think I can use more time this week.

👋 Hey, Thanks for working on this! No worries, take as long as you want, working on a new project takes a while.

This looks good to me, We need to remove the `target <arch>` since these ops are only implemented in the interpreter so far, otherwise everything should work!

**Comment by ArtBlnd** [comment]
I think there is some bitcast tests are missing. I am going to work on some bitcast tests before I start working implement float bitops on x86

**Review by jameysharp — APPROVED** [review]
This is great, thank you!

**Pull request merged**
