### PR TITLE
Cranelift AArch64: Migrate Bitselect and Vselect to ISLE

### PR DESCRIPTION
**Pull request by akirilov-arm**

### CODE REVIEW

**Review by cfallin — APPROVED** [review]
Thanks!

**Comment by cfallin** [comment]
cc @uweigand, looks like a `bitselect` failure on s390x with `i8` types in one of the new runtests.

(To get this in, I would be ok with splitting narrow-type bitops into a separate runtest file and omitting `target s390x` until fixed)

**Comment by cfallin** [comment]
That seems fine as a temporary measure. I'll file an issue to track completing support for skipped runtests on each platform in general; it's something we should definitely audit at some point.

**Comment by uweigand** [comment]
> cc @uweigand, looks like a `bitselect` failure on s390x with `i8` types in one of the new runtests.

Oops.  These were all supposed to be implemented, but it turns out the implementation of bitwise ops had a series of logic errors.  Fix is here: https://github.com/bytecodealliance/wasmtime/pull/4146

Thanks for catching this!

**Comment by akirilov-arm** [comment]
OK, I changed the test, so that it runs on all platforms except x86-64, where there is a failure.

**Review by cfallin — APPROVED** [review]
Thanks!

**Comment by cfallin** [comment]
cc @abrown for x86-64 test failure: would you mind taking a look, or at least triaging to some degree (miscompile, missing lowering, ...)?

**Pull request merged**
