### PR TITLE
Winch aarch64 cmp

### PR DESCRIPTION
**Pull request by vulc41n**
This PR implements wasm comparison instructions for winch targeting aarch64.
#8321

### CODE REVIEW

**Comment by saulecabrera** [comment]
I can help reviewing this change.

**Review by saulecabrera — COMMENTED** [review]
Sorry it took me a bit to review this change. In general it looks great to me, thanks. I left one nit below which I think it makes sense to address before merging.

**Review by saulecabrera — APPROVED** [review]
Thanks!

**Comment by vulc41n** [comment]
No problem, thanks for reviewing my pull request 🙂
I've removed `rd` from `subs` methods, but I do see `Wd` in the doc you linked. Am I missing something ?
Please tell me if there is anything else I can do to improve this

**Comment by saulecabrera** [comment]
> No problem, thanks for reviewing my pull request 🙂 I've removed `rd` from `subs` methods, but I do see `Wd` in the doc you linked. Am I missing something ? Please tell me if there is anything else I can do to improve this

Yeah, according to the docs there's a proper destination register, however, it's not currently used in the way we lower comparison operations in Winch, since we rely on the flags or in `cmp_with_set`, so my suggestion is mostly to make it easier to reflect the usage.

**Pull request merged**
