### PR TITLE
fuzzing: Enable NaN canonicalization

### LINKED ISSUE #1332: Canonicalize NaNs when fuzzing
In `Config::new` in `crates/api/src/runtime.rs`, we should conditionally enable the `canonicalize_nans` cranelift option when we're being built for fuzzing:

```rust
#[cfg(fuzzing)]
flags.set("enable_nan_canonicalization", "true").unwrap();
```

This should make execution during fuzzing that much more deterministic.

### PR DESCRIPTION
**Pull request by teapotd**
Enable NaN canonicalization when built for fuzzing. Fixes #1332.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for this!

I might actually differ a bit in a preference of how we go about doing this. I would advocate for a dedicated `Config` method being added for this which is then called explicitly when fuzzing. That way fuzzing is self-documented in the `Config` creation of the fuzzer and then this is also available to all other users too.

**Comment by teapotd** [comment]
Actually, shouldn't it belong to the `fuzzing` crate? It already creates config with some additional options by default:

https://github.com/bytecodealliance/wasmtime/blob/c202a8eeaf8f72a5e87d50ac2f0d58c9170b3488/crates/fuzzing/src/oracles.rs#L19-L29

I think it would be best to make it `pub` or `pub(crate)`, use it as base for custom configurations in entire `fuzzing` create and enable NaN canonicalization flag here.

**Comment by alexcrichton** [comment]
Yeah that's my thinking, we'd have a method on `Config` which is called by the `fuzzing` crate.

**Comment by teapotd** [comment]
No, I meant to have a function that creates appropriate `Config` in the `fuzzing` crate. `fuzz_default_config` is already in the `fuzzing` crate.

**Comment by alexcrichton** [comment]
@teapotd yes but the `fuzzing` crate depends on the `wasmtime` crate, and needs to call a public method on `Config` to enable nan canonicalization. The method needs to be defined in the `wasmtime` crate and then the `fuzzing` crate would call that.

**Comment by teapotd** [comment]
@alexcrichton Ah, that's what you meant. Thanks!

**Comment by alexcrichton** [comment]
Nice, thanks!

**Pull request merged**
