### PR TITLE
Patch release 0.32.1.

### PR DESCRIPTION
**Pull request by cfallin**
This is a patch release (nominally Cranelift, though also for Wasmtime due to process limitations at the moment) with cherry-picks of these three PRs: #3610, #3617, #3619. This fixes codegen bugs in Cranelift that prevented it from being used by cg_clif, and possible other consumers; any codegen bug is worthy of a patch release.

This is our first time using the [patch release process](https://github.com/bytecodealliance/wasmtime/actions/workflows/bump-version.yml); the PR merges the cherrypicked commits and a `RELEASES.md` update to a `release-0.32.1` branch in the main repo, and then we can trigger the version-bump/release workflow from there.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
👍 

Looks good to me, some minor things:

* Could the branch be called `release-0.32.0` or `release-0.32.x` or something like that? In theory we could do 0.32.2 in the future and we won't need a branch-per-release, just a branch-per-major-version.
* I think in theory there's a button on the GitHub UI where after this merges we can trigger the patch release which should send another PR to the repo for us to merge with version bumps.

**Comment by cfallin** [comment]
Cool, running the [version-bump](https://github.com/bytecodealliance/wasmtime/actions/runs/1594257673) job now with `bump-patch` as an argument, let's see if this works...

**Comment by cfallin** [comment]
OK, that job failed; I filed #3621 for the issue. It's probably a relatively simple fix, but not a one-liner, and might need some more debugging or run into other issues later in the process. I need to context-switch away to some other things before leaving for two weeks; so this patch release will have to wait (sorry @bjorn3) -- since the known consumer of Cranelift that runs into the 8/16-bit issues can pin to an earlier version for now, I don't think it's security-issue-level urgent.

**Comment by bjorn3** [comment]
I understand. I will push a commit to cg_clif to revert back to the previous cranelift release.

**Pull request merged**
