### PR TITLE
Support sealing blocks created by cranelift_frontend::Switch

### LINKED ISSUE #1323: Cranelift: `cranelift_frontend::Switch` does not support sealing created blocks.
Steps to reproduce:
- Structure code to seal blocks early (instead of sealing in bulk)
- Use `cranelift_frontend::Switch` to generate a sparse switch such that it generates chained comparisons instead of a jump table.
- Observe debug assertion regarding unsealed blocks.

Version:
- As of current HEAD (832666c45ead73fd833ea86da94cacb2f30a530c), there is no reference to `seal_block` in the `switch` module. Issue originally seen with `v0.58` from `crates.io`

### PR DESCRIPTION
**Pull request by teapotd**
This PR introduces a method to seal generated blocks during `emit` in `cranelift_frontend::Switch`. Fixes #1323.

### CODE REVIEW

**Comment by thepowersgang** [comment]
I'm wondering if the "correct" option would be to unconditionally seal, and change `seal_all_blocks` to ignore already-sealed blocks.

**Comment by teapotd** [comment]
Yes, I think it would be clearer. It would be a change in public API though. @alexcrichton what do you think?

**Comment by thepowersgang** [comment]
Would it be a visible change? Currently `seal_all_blocks` panics if there's previously-sealed blocks around, would it be a breaking change to make it not do that?

**Comment by bjorn3** [comment]
Technically it is a breaking change, but it is unlikely anyone depends on it. Besides breaking changes are regularly made to Cranelift. For example the change from EBB to BB and adding a `TrapSink` argument to `Module::define_function`.

**Comment by alexcrichton** [comment]
Sorry I don't know a lot about cranelift myself, so I don't have much advice on idioms/review/etc.

**Comment by teapotd** [comment]
Okay, I changed `seal_all_blocks` to ignore sealed blocks and `Switch::emit` to always seal generated blocks.

**Pull request merged**
