### PR TITLE
impl WasmTy for u32 and u64

### PR DESCRIPTION
**Pull request by leoyvens**
Wasm integer types are sign agnostic, so if Rust i32 and i64 are WasmTy so should u32 and u64. The trait implentation is exactly the same between i/u32 and i/u64.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Agreed these are good to have, thanks!

Some other items I think to take care of are:

* Could these be written in terms of the i32/i64 impls to cut down on duplication? 
* Can documentation be added to `Func::wrap` about these types?
* Can tests be added which exercise the presence of these impls?

**Comment by leoyvens** [comment]
@alexcrichton thanks for the review, I've addressed all points.

**Comment by alexcrichton** [comment]
Looks great to me! As one final nit, there's a table under "Rust types will map to WebAssembly types as follows", mind adding the u32/u64 types there too?

**Comment by leoyvens** [comment]
@alexcrichton ah of course, I missed that. Updated it.

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
