### PR TITLE
wasi common: move fs and path into Entry methods

### PR DESCRIPTION
**Pull request by pchickey**
based on #2201 

This PR refactors the bodies of all `fs` and `path` functions in snapshot 1 into `Entry` methods.

Anything that just requires an entry be in scope is moved to `entry/fd.rs`
and `entry/path.rs`, which just contain `impl Entry` blocks.

Additionally, the bodies of these functions were transformed so that as
much GuestPtr dereference as possible happens out in
wasi_snapshot_preview1.  Entry methods just get a `& T` or `&mut T`
passed in.

However, there are a few functions where multiple GuestPtrs are passed
into a wasi_snapshot_preview1 function. We cannot safely dereference
both at once, because it is semantically valid for these memory
regions to overlap, but the wiggle borrow checker will refuse to
borrow overlapping regions. In these cases, we have to pass the GuestPtr
into the Entity method to be dereferenced in a smaller scope where
exclusive access is possible.

Additionally, we make the minor transformation so that `crate::path::get` becomes
`Entry::path_get`. This moves from src/path.rs to src/entry/path.rs. This is just code
motion and doesn't make a difference.

### CODE REVIEW

**Comment by pchickey** [comment]
rebased on top of main after #2201 merged

**Review by sunfishcode — COMMENTED** [review]
Does moving the rights checks into `Entry` mean that the rights flags need to be the same between all snapshots? I expect the rights flags are an area that we'll want to evolve, so I'm interested in making sure we have a clear story here.

Is there anything we can say about the separation of responsibilities here? It's not immediately obvious what's `Entry`'s responsibility, what's `Handle`'s responsibility, and what's `WasiSnapshotPreview`'s responsibility.

**Comment by pchickey** [comment]
wrt the Rights flags: right now, the canonical definition of the rights type is in the witx snapshot, but if we evolve how rights work, I expect the first thing we'll do is make the canonical definition a type defined in wasi-common, and then define conversion functions for whenever we need to represent those to the guest via each snapshot we support.

wrt separation of responsibilities: first off, theres a big overlap between `Handle` and `Entry` right now, which needs design work still. I'm not 100% sure how to resolve these yet. My goal is that the handle/entry concept will be responsible for exporting all types used in its interfaces. Whether those types are imported from a given snapshot's wiggle generated code, or defined canonically without wiggle, is an implementation detail.

At the moment, snapshots manipulate the entry table (mostly `get_entry` but some `remove_entry` and `insert_entry_at`) and call `Entry` methods (though they do so with types exported by `crate::handle`... admittedly this is muddled). Since we want to define many snapshots that will usually look a lot alike, I tried to move as much complexity out of these bodies as possible, while exposing as few pointers (and, with them, assumptions about how guest programs represent things in memory) to the `Entry` methods as possible. Unfortunately, I haven't figured out how to do this with absolutely no pointers, unless we reintroduce mut vs const borrows to the wiggle api so that const borrows can overlap.

Then, each snapshot will be responsible for calling the handle/entry concept, converting any of its interfaces's types to and from the ones expected by the `Entry` methods. Whichever snapshot's types get exported by `crate::handle` gets to skip this converting to/from code. For all of the types in snapshot 0, we'll have to define conversion functions, but the overwhelming majority of them should compile to a no-op because the representation is exactly the same.

This PR leaves this work incomplete - #2205 is still a work in progress at completing that abstraction with the scheduler methods.

**Comment by pchickey** [comment]
Closing, I'm taking another tack on this work based on cap-std & system-interface.

**Pull request closed without merging**
