### PR TITLE
Update Cranelift to 0.52.0

### PR DESCRIPTION
**Pull request by abrown**
This PR is a bit premature (since Cranelift v0.52.0 has not yet been published) but as I attempt to get SIMD spec tests working I need changes like these to build my locally-changing copy of Cranelift. In talking to @yurydelendik I agreed to push these, but please note the `unimplemented!` used in the newly-exposed methods.

[edit: this PR should be good for review now that 0.52.0 is published]

### CODE REVIEW

**Comment by abrown** [comment]
It looks like `wasi_tests` are failing on [test (beta)](https://github.com/bytecodealliance/wasmtime/pull/710/checks?check_run_id=354907618#step:8:196)--@sunfishcode, any ideas?

**Comment by kubkon** [comment]
> It looks like `wasi_tests` are failing on [test (beta)](https://github.com/bytecodealliance/wasmtime/pull/710/checks?check_run_id=354907618#step:8:196)--@sunfishcode, any ideas?

It's also failing on `nightly`. This looks like an ABI incompatibility. Perhaps @alexcrichton will have more ideas about this?

**Comment by kubkon** [comment]
@abrown @alexcrichton I’ll update the remaining WASI tests to use the latest `wasi` crate and this should make the CI green again. I’ll cc you guys in when the PR is ready and @abrown you’ll be able to rebase onto it for your PR to pass the CI.

**Comment by alexcrichton** [comment]
I think it's probably best to disable the wasi tests on beta for now, we can re-enable when it's fixed again. I believe the current bug is https://github.com/rust-lang/rust/pull/67363 and needs to be fixed by either (a) moving everything to the `wasi` crate or (b) waiting for that PR to land. I'm not 100% certain though about whether that PR will simply fix things, soin the meantime feel free to disable beta to land things in the interim.

**Comment by kubkon** [comment]
> I think it's probably best to disable the wasi tests on beta for now, we can re-enable when it's fixed again. I believe the current bug is [rust-lang/rust#67363](https://github.com/rust-lang/rust/pull/67363) and needs to be fixed by either (a) moving everything to the `wasi` crate or (b) waiting for that PR to land. I'm not 100% certain though about whether that PR will simply fix things, soin the meantime feel free to disable beta to land things in the interim.

I've now migrated all WASI test programs to `wasi` 0.9.0 in #743, so we should be green with the test jobs. However, now Emscripten job started failing also, and I'm wondering what to do. I suggested to @sunfishcode that we could either disable it or move the job from stable to nightly toolchain to get rust-lang/rust#66308 quicker. Thoughts?

**Comment by kubkon** [comment]
@abrown @alexcrichton I've now filed #744 which disables the Emscripten job until rust-lang/rust#66308 is resolved.

**Comment by abrown** [comment]
@kubkon, I rebased on your merged #744 but it still fails; did #744 fix the issue because I still see failures on [HEAD](https://github.com/bytecodealliance/wasmtime/commits).

**Comment by kubkon** [comment]
@abrown oh sorry, we still need #743 to land for the CI to be completely in the green.

**Comment by yurydelendik** [comment]
Thank you.

**Pull request merged**
