### PR TITLE
wasmtime-cache: Update zstd

### PR DESCRIPTION
**Pull request by olivierlemasle**
[Update](https://github.com/gyscos/zstd-rs/compare/0.6.1...0.9.0) zstd dependency

Also update exceptions in deny.toml bans

### CODE REVIEW

**Comment by olivierlemasle** [comment]
CI fails in "verify-publish" because `cargo vendor` copies crate `zstd-sys` without its [submodule](https://github.com/gyscos/zstd-rs/blob/master/.gitmodules). For a reason I don't understand, the [crate contains `zstd/lib`](https://crates.io/api/v1/crates/zstd-sys/1.6.0+zstd.1.5.0/download), however when using `cargo install`, the `zstd` directory is not copied...

**Comment by alexcrichton** [comment]
I dug in a bit and I believe this is a [bug in Cargo](https://github.com/rust-lang/cargo/issues/9555). For now the best fix though is to probably send a PR to `zstd-sys` to update the `exclude` directive to work in a way both for publication and vendoring. Unfortunately I don't think we can land this as-is until CI is green again.

**Comment by olivierlemasle** [comment]
Thank you for your analysis @alexcrichton. I was actually also looking at this `list_files` function...

> Unfortunately I don't think we can land this as-is until CI is green again.

Of course! I'll mark this PR as a draft in the meantime.

**Comment by alexcrichton** [comment]
Thanks again!

**Pull request merged**
