### PR TITLE
Add support for WASI sockets to C API

### LINKED ISSUE #5071: Add WASI sockets support to the C API
#### Feature

The `wasmtime` CLI supports the `--tcplisten` and `--listenfd` options for WASI sockets support, but the C API is missing support for these same WASI socket features. This issue is to track adding support for WASI networking in the C API.

#### Benefit

This aids the ability for C applications that leverage the wasmtime C shared library API for executing WASM modules to support networking features for those modules.

#### Implementation

The existing WASI networking features that are supported in the `wasmtime` CLI code path need to be plumbed through to the C API. For example, this will involve expanding the `wasi_config_t` struct to add a field for preopened sockets as well as a new `wasi_config_preopen_socket` API for populating this new `wasi_config_t` preopened sockets field.

### PR DESCRIPTION
**Pull request by font**
This adds support for WASI sockets to the C API by adding a new API to handle preopening sockets for clients. This uses `HashMap` instead of `Vec` for preopened sockets to identify if the caller has called in more than once with the same FD number. If so, then we return false so caller is at least given a hint that they may be misusing the API e.g. attempting to overwrite an already existing socket FD.

I stuck with the same `bool` return value because it was already being done for the other APIs e.g. `wasi_config_preopen_dir`. I think it would be beneficial to have a more specific error type, if possible, but not something to address in this PR.

I don't think there are any tests for these APIs so none were added. Of course I was personally testing this with the `crun` container runtime that is using these APIs.

I don't know who could review this so any help identifying the right people would be greatly appreciated!

Fixes #5071

### CODE REVIEW

**Comment by font** [comment]
@peterhuene Do you think you would be able to help with this review?

**Review by peterhuene — COMMENTED** [review]
Hi @font! Thanks for the PR. The changes look good, just some minor feedback comments to go over.

**Review by font — COMMENTED** [review]
@peterhuene thank you for your review! I've incorporated all of your feedback in new commits that should be squashed and this is now ready for another review.

**Comment by font** [comment]
@peterhuene Do you think you would be able to help re-review?

**Comment by peterhuene** [comment]
Shoot, sorry @font, this fell off my radar. I'll review it shortly.

**Review by peterhuene — APPROVED** [review]
👍 Thanks for implementing this!

**Pull request merged**
