### PR TITLE
Pch/runtime wasi nn

### PR DESCRIPTION
**Pull request by pchickey**

### CODE REVIEW

**Comment by pchickey** [comment]
cc @abrown lets see if this fixes the weird issue on windows

**Comment by abrown** [comment]
Took the liberty to remove an unused dependency with 5017d90; let's see what happens now...

**Comment by abrown** [comment]
@pchickey, cool, looks like that solved it! I guess the remaining thing to do is figure out if the project is OK allowing ISC licenses, described [here](https://choosealicense.com/licenses/isc/). I would lean towards allowing them, since they are not much different than MIT...

**Comment by abrown** [comment]
Thanks @pchickey, this solved the issue. I cherry-picked your commit over to #2859 so I'm going to close this.

**Pull request closed without merging**
