### PR TITLE
Implement `SwidenLow` and `SwidenHigh` for the interpreter

### PR DESCRIPTION
**Pull request by dheaton-arm**
Implemented `SwidenLow` and `SwidenHigh` for the Cranelift interpreter,
doubling the width and halving the number of lanes preserving the low
and high halves respectively.

Conversions are performed using signed extension.

Copyright (c) 2021, Arm Limited

### CODE REVIEW

**Review by cfallin — COMMENTED** [review]
Same comment as in #3316 re: iterator chain.

Also, I wonder if it would make sense to factor out most of the commonality between signed and unsigned cases? Something like `let is_signed = match op { ... };` then `if is_signed { ValueConversion::... } else { ValueConversion::... }` in the per-lane expression. Helpers could be defined as desired here (`.is_signed()` on opcode to disambiguate signed/unsigned opcodes, returning an `Option<bool>` that is `None` if there is no signedness/unsignedness?)

**Comment by dheaton-arm** [comment]
Happy to address the iterator chain comment.

Regarding the idea to factor out commonality between un/signed cases, I think that would work, but may be easier to do (given that the unsigned and signed variants are in separate branches / PRs at the moment) either as a follow-up patch after both of these are merged, or after one of them merge and then implemented in the remaining PR.

**Comment by cfallin** [comment]
Yep, a followup that factors things appropriately (maybe across any other signed/unsigned pairs as appropriate too) would be perfectly fine, thanks!

**Review by cfallin — APPROVED** [review]
Thanks for the updates, looks great!

**Pull request merged**
