### PR TITLE
bump tokio-rustls

### PR DESCRIPTION
**Pull request by arlyon**
Note that rustls is not on the latest minor since tokio-rustls
has not updated yet.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR!

Per [project policy](https://docs.wasmtime.dev/contributing-coding-guidelines.html#dependencies-of-wasmtime) we require `cargo vet` entries for all our dependencies, so we'll project maintainers to vet these new dependencies and push them either as a parallel PR for this to rebase onto or to this PR itself.

I checked initially and these are pretty substantial updates to vet, so to help motivate a bit, can you detail a bit more why this is needed? Is this a "generally good to stay up to date" style PR or perhaps more urgent along the lines of "must fix a bug" or "must only have one library in the crate graph" style problem?

**Comment by alexcrichton** [comment]
I was additionally inspired by this PR and brought up `cargo vet` at today's Wasmtime meeting which led to https://github.com/bytecodealliance/wasmtime/pull/8259 which will relax the vet rules slightly here.

**Comment by alexcrichton** [comment]
Ok under our [new policy](https://github.com/bytecodealliance/wasmtime/pull/8259) for vets I've added necessary exemptions to this PR. I've additionally updated the `ureq` dependency silghtly to avoid pulling in two versions of rustls/ring.

Thanks for the patience here @arlyon!

**Comment by arlyon** [comment]
No worries I realise you ended up doing most of the work here so I appreciate the effort. Have a nice weekend! :)

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
