### PR TITLE
cranelift: Add `fadd`/`fsub`/`fmul`/`fdiv` to interpreter

### PR DESCRIPTION
**Pull request by afonso360**
👋  Hey,

Fuzzgen found that we were missing these as soon as I added float support

### CODE REVIEW

**Review by jameysharp — APPROVED** [review]
I'm still learning the details of the WebAssembly spec so I have a couple questions, but overall I think this looks good.

I expected to see fdiv tests for the case of a non-zero value divided by zero, which I assumed would return NaN, but I didn't see such tests in that section. Did I miss something?

In the implementation of the interpreter, would it make sense to have all integer values be represented using [std::num::Wrapping](https://doc.rust-lang.org/std/num/struct.Wrapping.html)? Then I think all the uses of `binary_match!` that you updated here could just use e.g. `+(self, other)` for both integer and floating point types, and you wouldn't need an `is_float` function.

**Comment by afonso360** [comment]
> I expected to see fdiv tests for the case of a non-zero value divided by zero, which I assumed would return NaN, but I didn't see such tests in that section. Did I miss something?

You're absolutely right, we are missing those cases. Ill add them.

> In the implementation of the interpreter, would it make sense to have all integer values be represented using [std::num::Wrapping](https://doc.rust-lang.org/std/num/struct.Wrapping.html)? Then I think all the uses of binary_match! that you updated here could just use e.g. +(self, other) for both integer and floating point types, and you wouldn't need an is_float function.

That sounds like a good idea for the interpreter. However `DataValue` is shared with the rest of the compiler and I think that will have some knock on effects which I'm not quite sure of the implications that would bring.

I'm willing to try and make that change if you think its worth it.

**Comment by afonso360** [comment]
I think we have them all now. Thanks for reviewing this!

**Comment by jameysharp** [comment]
You're welcome! Code review is good for me, I learn things. :laughing:

Did you mean to comment out `test interpret` in that last force-push, or was that an accident?

**Comment by afonso360** [comment]
Oops, should be fixed now.

**Pull request merged**
