### PR TITLE
x86_32: legalize br{z,nz}.i64

### PR DESCRIPTION
**Pull request by whitequark**
As requested in https://github.com/bytecodealliance/wasmtime/pull/1788#issuecomment-636307297 (the right branch this time).

### CODE REVIEW

**Comment by bjorn3** [comment]
There are macOS failures again.

**Comment by tschneidereit** [comment]
But this time a retrigger apparently fixed it? 🙃

**Comment by whitequark** [comment]
Is there anything blocking the merge of this?

**Comment by abrown** [comment]
Sorry!

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
