### PR TITLE
egraphs: Recognize `bitselect` from bitwise operations

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey,

While working on #6876, I noticed we don't yet recognize this pattern for bitselects. I've also added the various permutations of this rule since I don't think we rotate inputs on bitwise operations. (And my understanding is that we shouldn't do so)

### CODE REVIEW

**Review by fitzgen — COMMENTED** [review]
LGTM, but can we please add some runtests as well? Thanks!

A bit of an aside, but it also makes me think that we should make the runtest runner automatically run tests twice, once with optimizations and once without them. Because we want that for every single runtest that exercises any mid-end rewrite rule, and it definitely doesn't hurt for runtests that are just stressing lowering or something.

**Comment by afonso360** [comment]
Looks like the x86 backend does not have scalar bitselect implemented. I'm going to try to work on that so that we don't an optimization that generates code that can't be lowered.

**Comment by afonso360** [comment]
I've restricted this transform for vectors only since each backend implements a different subset of `bitselect`. Maybe we can derestrict this a little bit more once the backends are slightly more complete.

**Review by jameysharp — APPROVED** [review]
That's a good restriction to adopt for now and a good assortment of new tests. Thanks!

**Pull request merged**
