### PR TITLE
Fix compilation error due to redefinition.

### PR DESCRIPTION
**Pull request by AlexEne**
Fixed a compilation error due to a redefinition of `wasmtime_profiling_strategy_t` as an enum as well as int8_t typedef.
I don't know who can review this, but I would be grateful if someone could take a look, as it's a trivial change.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm curious, though, how did this turn into an error? We're compiling the C examples on CI which in theory would catch this. Is there a way we can catch this on our own CI?

**Comment by AlexEne** [comment]
I just tried to use this in my project. I am surprised that the C examples compile in your CI? 
I'm using clang on OSX and was basically going through the example code trying to instantiate a VM.  
Maybe it gets ignored on certain compilers if the symbol isn't referenced at all?

**Comment by alexcrichton** [comment]
Hm we're compiling the examples on macOS as well, so we should see it there if it's an issue. Do you perhaps have some extra warnings or such turned on which would cause this to be an error?

**Comment by AlexEne** [comment]
I do have warnings set as errors, however this looks like it's a hard error, not a warning: 

```
In file included from myfile.cpp:2:
wasmtime/crates/c-api/include/wasmtime.h:42:6: error: definition of type 'wasmtime_profiling_strategy_t' conflicts with typedef of the same name
enum wasmtime_profiling_strategy_t { // ProfilingStrategy
     ^
wasmtime/crates/c-api/include/wasmtime.h:41:17: note: 'wasmtime_profiling_strategy_t' declared here
typedef uint8_t wasmtime_profiling_strategy_t;
```

**Comment by AlexEne** [comment]
Just to clarify this is an error when compiling a host VM that's written in C++ that wants to use WASMTime, not an error in compiling C->WASM (I did find some of these tested in the nightly runs).

**Comment by peterhuene** [comment]
This is indeed illegal in C++ and we don't have any examples that include `wasmtime.h` from a C++ source file (clang and gcc both use the file extension to default the language).

We should probably add a `hello.cc` to `examples/` to catch this in CI.

**Comment by AlexEne** [comment]
I added a new file, I wanted initially to just rename `hello.c` -> `hello.cc`, but I noticed that you refernce it in some places as a C example and I don't know how strongly you feel about C/C++ distinction so I left both in there.

**Comment by alexcrichton** [comment]
Ah nice find! I think though to run these examples we'll need to add support [to this runner](https://github.com/bytecodealliance/wasmtime/blob/f84903fa430228afe4306e7b1bf5a57ace0d4497/crates/misc/run-examples/src/main.rs#L54-L70) as well.

**Comment by AlexEne** [comment]
Ah, so that's where it was, I will add it to the file.

**Comment by AlexEne** [comment]
I've added a way for tests to also compile and run any `.cc` files found, in additon to the `.c` files. The C++ files are optional so if none are found they are skipped, but if  `.c` files are missing tests will fail as before.

Output:
```
======== C/C++ example `hello` ============
Running for file: "examples/hello.c"
Initializing...
Loading binary...
Compiling module...
Instantiating module...
Extracting export...
Calling fib...
> fib(6) = 21
Shutting down...
Done.
Running for file: "examples/hello.cc"
Generating Code...
Compiling...
Generating Code...
hello.obj : warning LNK4042: object specified more than once; extras ignored
Initializing...
Loading binary...
Compiling module...
Instantiating module...
Extracting export...
Calling fib...
> fib(6) = 21
Shutting down...
Done.
```

**Comment by peterhuene** [comment]
Thanks for fixing this and adding a test case!

**Pull request merged**
