### PR TITLE
Switch macOS to using mach ports for trap handling

### LINKED ISSUE #2456: Consider adding support for MacOS exception ports
Currently, wasmtime hooks various signals in traphandlers on Unix platforms before executing wasm code so that it can catch and handle various runtime issues without actually crashing the host program. However, on MacOS there is an additional error handling mechanism, [Mach Exceptions](https://flylib.com/books/en/3.126.1.109/1/). By default a Mach exception will be turned into a unix signal, however, if the application binds their own exception port via `task_set_exception_ports` or similar, it's up to that handler to actual forward to the default signal mechanism, but in most cases they will probably just abort the process instead, even though wasmtime would have successfully recovered program execution in its signal handler.

#### Feature

The feature I'm proposing would be for wasmtime's traphandler to use exception ports when targeting MacOS (and I guess iOS, but I would assume that target is not relevant for wasmtime due to its code execution rules?), forwarding exceptions to whatever previously registered exception port if the exception is not one of the one's wasmtime wants to handle.

#### Benefit

The application could have previously registered signal handlers or exception ports on Mac and still function as expected whenever wasmtime executes exceptional wasm code.

#### Implementation

\* I think basically the implementation is mostly conceptually the same as the current signal handling approach, but basically it would be something like...

1. Store the previous exception port(s)
1. Set exception port to wasmtime's own handler
1. When entering trap handling, signal to the handler thread (shared memory, ipc, whatever) that the handler should treat the exceptions it can handle (the equivalents of the SIGILL etc) as runtime errors, but all other exceptions, or when not executing wasm code, should be forwarded to the previous exception port(s)
1. When exiting trap handling, tell the handler thread to always forward exceptions

Also, one thing that would possibly make this easier would just be to directly signal the thread, similar to Mac's own ux_handler code as seen [here](https://opensource.apple.com/source/xnu/xnu-201.5/bsd/uxkern/ux_exception.c.auto.html).

\* All of this information is gleaned from [Mach Exceptions](https://flylib.com/books/en/3.126.1.109/1/), [Signas](https://flylib.com/books/en/3.126.1.110/1/), and [Breakpad's Exception Handler](https://github.com/google/breakpad/blob/master/src/client/mac/handler/exception_handler.cc), as the official Apple documentation is, frankly, garbage.

#### Alternatives

The alternative would just be to not do this at all, but in that case I think having a warning in the documentation somewhere so that people running wasmtime on a Mac are aware that having `task*_set_exception_ports` in their program might mean that wasmtime's normal behavior of catching and handling exception wasm code won't even execute depending on how the user exception handler is implemented.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit moves macOS to using mach ports instead of signals for
handling traps. The motivation for this is listed in #2456, namely that
once mach ports are used in a process that means traditional UNIX signal
handlers won't get used. This means that if Wasmtime is integrated with
Breakpad, for example, then Wasmtime's trap handler never fires and
traps don't work.

The `traphandlers` module is refactored as part of this commit to split
the platform-specific bits into their own files (it was growing quite a
lot for one inline `cfg_if!`). The `unix.rs` and `windows.rs` files
remain the same as they were before with a few minor tweaks for some
refactored interfaces. The `macos.rs` file is brand new and lifts almost
its entire implementation from SpiderMonkey, adapted for Wasmtime
though.

The main gotcha with mach ports is that a separate thread is what
services the exception. Some unsafe magic allows this separate thread to
read non-`Send` and temporary state from other threads, but is hoped to
be safe in this context. The unfortunate downside is that calling wasm
on macOS now involves taking a global lock and modifying a global hash
map twice-per-call. I'm not entirely sure how to get out of this cost
for now, but hopefully for any embeddings on macOS it's not the end of
the world.

Closes #2456

### CODE REVIEW

**Comment by alexcrichton** [comment]
One thing worth pointing out is that I believe Wasmtime currently complies for arm64 macOS (although it doesn't work AFAIK), but this PR would break that. Structures for the thread state would need to be copied over from various headers to get that working.

**Comment by Jake-Shadle** [comment]
We actually run aarch64 mac CI on our project that uses wasmtime, so I think we can just add a PR that builds off of this one for the aarch64 specific things that would need to change. :slightly_smiling_face:

**Comment by Jake-Shadle** [comment]
Oh wait, I was just reminded that we _might_ not be able to verify this PR on the aarch64 mac though, due to https://github.com/bytecodealliance/wasmtime/issues/2552, we actually had to disable the tests we had that purposefully paniced inside the wasm module for aarch64 mac due to it actually crashing our host program.

**Comment by alexcrichton** [comment]
Ah ok, I didn't realize it already worked well enough to at least have some testing! I've pushed up https://github.com/bytecodealliance/wasmtime/pull/2632/commits/d07d29b83f92a66c761fc9f207f93a60e3f7562e although it is entirely untested on my end (I don't have arm64 hardware). It should compile but I suspect at least some tests fail.

**Comment by Jake-Shadle** [comment]
Great, thanks!

**Comment by bnjbvr** [comment]
I've based my work in #2723 from this PR, which has been rebased and tweaked. Thanks a lot @alexcrichton for all the initial work on this!

**Pull request closed without merging**
