### PR TITLE
refactor: Replace lazy-static with LazyLock

### PR DESCRIPTION
**Pull request by howjmay**

### CODE REVIEW

**Comment by bjorn3** [comment]
`OnceLock` has been stabilized in rust 1.70, but `LazyLock` hasn't yet.

**Comment by howjmay** [comment]
@bjorn3 sorry let me open another PR for OneLock

**Comment by jameysharp** [comment]
I think this is a great idea. I always love getting rid of dependencies.

But this is only stabilized in 1.70, right? We're having issues building Wasmtime with 1.70 for two of our target platforms (risc-v and s390). As far as I understand, the issues we've run into will be fixed by 1.71, so I don't think we're going to try to work around the 1.70 issues.

As a result, I would like to wait on merging this until 1.71 is out. But at that point I am interested in merging this! Please remind me to look at this again once that release is out.

**Comment by howjmay** [comment]
@jameysharp this is great! Thanks!

**Comment by alexcrichton** [comment]
@howjmay if you're up for it Rust 1.71.0 is now released and we've updated CI to use it, so if you're still up for rebasing this now'd be a prime time to do so

**Comment by howjmay** [comment]
Hi @alexcrichton ! I have rebased my PR to the lasted commit on `main`, but it failed for unknown reason

**Comment by alexcrichton** [comment]
It looks like you've accidentally changed a submodule here, and additionally this is using `#![feature(lazy_cell)]` which requires nightly but Wasmtime builds with stable so I don't think that will work as well unfortunately.

**Comment by sunfishcode** [comment]
Wasmtime's lazy-static dependency has since been removed in #4368 and #4383.

**Pull request closed without merging**
