### PR TITLE
Remove rss prediction from api_calls fuzzer

### PR DESCRIPTION
**Pull request by alexcrichton**
This functionality is now subsumed by the limiter built-in to all
fuzzing stores, so there's no longer any need for it. It was also
triggering arithmetic overflows in fuzzing, so instead of fixing I'm
removing it!

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Kind of feel like maybe we can completely remove this fuzz target?

**Comment by alexcrichton** [comment]
Personally I think the fuzz target is still good to have. It's the only fuzz target that can exercise a variable number of modules/instances within the store (although they still aren't linked to one another). I do think that its usefulness has decreased over time but not to the point that I think it should go away. 

It's also theoretically a great place to add more API calls in the future too!

**Comment by fitzgen** [comment]
Well module linking exercises multiple modules/instances in the same store now. But sure.

**Comment by alexcrichton** [comment]
Oh, true! In that case I think you're right in that this may have outlived its usefulness a bit. I don't mind either way though.

**Pull request merged**
