### PR TITLE
Add wasmtime.h and wasi.h to package

### PR DESCRIPTION
**Pull request by yurydelendik**
We are not including these files in the distribution packages. This PR fixes that.

### CODE REVIEW

**Comment by rene-fonseca** [comment]
Change is fine.

Except include issue for wasmtime.h - it uses #include <wasm.h>.
Best to use #include "wasm.h".

The includes should be consumed as if installed under a "wasmtime" subfolder ideally (e.g. /usr/include/wasmtime). And that means it would be the parent folder (ie. /usr/include) that is in the include search path. And #include <wasm.h> would then not work.

That way there wont be any include conflicts. Which can easily happen if other WASM engines are in the include search path.

**Comment by yurydelendik** [comment]
> The includes should be consumed as if installed under a "wasmtime" subfolder ideally (e.g. /usr/include/wasmtime). And that means it would be the parent folder (ie. /usr/include) that is in the include search path. And #include <wasm.h> would then not work.

Can you file a separate issue for that? Currently we are using these files in [the 'make run-config-debug-c' example](https://github.com/bytecodealliance/wasmtime/blob/master/crates/c-api/examples/Makefile#L161) and it does not look like it is the problem.

**Comment by rene-fonseca** [comment]
Sure. I'll do it once I have reviewed new headers locally. There might be other stuff.

**Comment by rene-fonseca** [comment]
Opened issue https://github.com/bytecodealliance/wasmtime/issues/1215 for wasmtime.h . 3 simple issues to make it compile.

**Pull request merged**
