### PR TITLE
Replace the global-exports mechanism with a caller-vmctx mechanism.

### PR DESCRIPTION
**Pull request by sunfishcode**
This eliminates the global exports mechanism, and instead adds a
caller-vmctx argument to wasm functions so that WASI can obtain the
memory and other things from the caller rather than looking them up in a
global registry.

This replaces #390, and updates it for a lot of the changes in the tree.

This is a draft which should be mostly complete, though it needs https://github.com/bytecodealliance/cranelift/pull/1329 in Cranelift first, and and it needs general polishing and testing.

### CODE REVIEW

**Comment by sunfishcode** [comment]
https://github.com/bytecodealliance/cranelift/pull/1329 has landed, but we need another fix now: https://github.com/bytecodealliance/cranelift/pull/1337.

**Comment by alexcrichton** [comment]
I've pushed up a merge and a number of fixes to this, and this'll require https://github.com/bytecodealliance/cranelift/pull/1352 to land as well eventually. Still tracking down one final set (hopefully) of segfaults.

**Comment by alexcrichton** [comment]
Ok the final segfault I was seeing is https://github.com/bytecodealliance/wasmtime/pull/830, so I think this is good to go once cranelift is updated

**Comment by alexcrichton** [comment]
Ok I think this should be good to go now! @sunfishcode would you be ok reviewing or should I tag some other folks in?

**Pull request merged**
