### PR TITLE
Implement fmin_pseudo and fmax_pseudo for scalars

### PR DESCRIPTION
**Pull request by bjorn3**

### CODE REVIEW

**Comment by cfallin** [comment]
Would you mind adding tests (probably runtests, constrain to x64-only for now unless aarch64 happens to support this already)?

**Comment by bjorn3** [comment]
There don't seem to be any tests for fmin_pseudo and fmax_pseudo at all.

**Comment by cfallin** [comment]
> There don't seem to be any tests for fmin_pseudo and fmax_pseudo at all.

Yes, exactly; no better reason than that to add some (and thanks!) :-) It's odd that the vector variants don't have tests; you could either add that too if it's not too much work, or just leave it for another PR (maybe file an issue?) otherwise.

The PR at WebAssembly/simd#122, referenced in the instructions' description text, has some examples of how pseudo-min/pseudo-max differ from true min/max, specifically w.r.t. NaNs and signed zeroes. I think it makes sense to add a test with a few input tuples from those examples, along with some more ordinary cases.

**Review by cfallin — APPROVED** [review]
Looks good with new tests -- thanks!

**Pull request merged**
