### PR TITLE
WASI: make O_CREAT|O_TRUNC actually truncate files on Windows

### LINKED ISSUE #2009: Opening files with O_TRUNC does not truncate them on Windows
Consider the following program:
```cc
#include <fstream>

int main() {
	std::ofstream ff;
	ff.open("test.txt", std::ofstream::trunc);
	ff << "bad bad bad bad\n";
	return 0;
}
```
I've attached it here:  [bad.zip](https://github.com/bytecodealliance/wasmtime/files/4903795/bad.zip)

Open `test.txt` and put something like this there:
```
bad bad bad bad
this will remain here
```

Run it:
```
wasmtime run --dir . bad.wasm
```

The file is not truncated.

### PR DESCRIPTION
**Pull request by whitequark**
Fixes #2009.

### CODE REVIEW

**Comment by whitequark** [comment]
> Would it be possible to add your test case (ported to a test-programs test maybe) to ensure we don't regress this fix?

Sorry, I'm not familiar with this part of wasmtime's testing infrastructure, and the test case is pretty dirty (as-is it uses libc++...). If you have a step-by-step guide for doing this I could do it though!

**Comment by peterhuene** [comment]
No worries!  There's a bunch of tests in `crates/test-programs/wasi-tests` that use the `wasi` crate to directly test against the Wasmtime's WASI API surface.

I think a new test case in there that creates a file with some text, closes it, and then opens it with `OFLAGS_CREAT` AND `OFLAGS_TRUNC`, then reads it to confirm it is truncated would do the trick.

I'd be happy to write one if you would like.

**Comment by whitequark** [comment]
> I'd be happy to write one if you would like.

Please do, that would help a lot.

**Comment by kubkon** [comment]
> No worries! There's a bunch of tests in `crates/test-programs/wasi-tests` that use the `wasi` crate to directly test against the Wasmtime's WASI API surface.
> 
> I think a new test case in there that creates a file with some text, closes it, and then opens it with `OFLAGS_CREAT | OFLAGS_TRUNC`, then reads it to confirm it is truncated would do the trick.
> 
> I'd be happy to write one if you would like.

Would it make sense to modify [truncation_rights.rs](https://github.com/bytecodealliance/wasmtime/blob/main/crates/test-programs/wasi-tests/src/bin/truncation_rights.rs) instead of/in addition to adding a new one? It seems this one should already test what has been discussed here, but due to the fact the file is always empty and never reopened, this bug was missed on Windows.

**Comment by peterhuene** [comment]
I think that `truncation_rights` is specifically centered around the WASI right checking whereas the new test would be simply to check that `OFLAGS_TRUNC` was respected properly for `path_open`.

Personally I'd prefer two smaller tests to one complicated test.

**Comment by peterhuene** [comment]
@kubkon I've pushed up a test case for file truncation.  Would you mind reviewing it?  I've confirmed the test fails without @whitequark's fix and passes with the fix on Windows.

**Comment by peterhuene** [comment]
Third time's a charm on those force pushes (I was lazy and just `cargo test --feature test_programs` the test programs crate directly, which doesn't error on unused imports when building).

**Comment by peterhuene** [comment]
@whitequark thanks for fixing this!

**Pull request merged**
