### PR TITLE
`--json` option for `wasmtime settings` command

### PR DESCRIPTION
**Pull request by martindevans**
Added a `--json` flag to the `wasmtime settings` command, as discussed in #5404. Settings data is gathered into the `Settings` struct, which is then printed either in human readable form (exactly the same format as before) or JSON (using serde).

I'm not very familiar with Rust, so please tell me if I've done any weird non-idiomatic things and I'll try to fix them!

### CODE REVIEW

**Comment by martindevans** [comment]
I'm not quite sure what the `cargo deny` and `cargo vet` failures are indicating. I need some guidance on how to fix those failures.

**Comment by jameysharp** [comment]
Ah, you picked newer versions of serde and serde-json than we're using in the rest of the project, and nobody has vetted those versions or their dependencies yet. If you switch to serde 1.0.94 and serde_json 1.0.26, I believe all the cargo deny/vet errors will go away.

**Comment by martindevans** [comment]
Thanks, I'll try that.

**Comment by jameysharp** [comment]
I think you'll need to re-run cargo to update `Cargo.lock` too. I think `cargo check` should be enough.

**Comment by martindevans** [comment]
Looks like CI is passing this time, thanks for your help @jameysharp ❤️

**Review by alexcrichton — APPROVED** [review]
Thanks!

**Pull request merged**
