### PR TITLE
riscv64: Refactor and enable optimizing sign extensions

### PR DESCRIPTION
**Pull request by alexcrichton**
This PR is a long series of commits which is a culmination of some investigation and poking around I've been doing after taking a look at https://github.com/bytecodealliance/wasmtime/pull/7113. Previously there were quite a few entry points into the core `extend` function in the riscv64 backend which all had a number of different concerns handled and felt, at least from my perspective, a bit confusing to follow. The goal of this refactoring was to canonicalize around two helper functions, `zext` and `sext`, which take no arguments except a `Value`. The functions would then internally do whatever is necessary to extend to the full register width and an `XReg` would be returned.

This required quite a bit of refactoring and changes to the previous code such as:

* Handling of 128-bit values was pushed into callers that needed it to avoid needing to have all callers deal with the possibility of 128-bit values.
* Many functions were moved around to be able to pass in a `Value` vs a `XReg Type` combo. This involved a lot of movement from `inst.isle` into `lower.isle` as well as code motion.
* Many helpers which called each other now bottom out much more quickly or have a little bit more duplication in `lower.isle`. Personally I felt the duplication was relatively small and ok, but other reviews are welcome!
* All extension-related helpers are removed now except `zext` and `sext` which internally have all conditional logic as necessary.

The final culmination of this PR is that the assembly output probably doesn't change all that much for the time being. There's now a clear place, however, to skip sign extension based on the structure of a `Value`. For example I'd like to add support for the `addw` instruction which would skip the need to sign-extend the result of a 32-bit add. Similarly for other 32-bit operations as necessary. This is all in preparation for optimizing `icmp` which always has to sign extend so the goal in theory is to remove as many sign extension as possible.

### CODE REVIEW

**Review by afonso360 — APPROVED** [review]
I really like this! Thanks for these cleanups!

I like the `val_already_extended` approach, and I think we may be able to fit a few more ops in it like `fcmp`, `{s,u}load{8,16,32}` and `bmask` (with some restrictions)! I might do a follow up PR if you don't do it first.

> For example I'd like to add support for the addw instruction which would skip the need to sign-extend the result of a 32-bit add. Similarly for other 32-bit operations as necessary.

I should note that we already have support for these operations, but they are all in the [`sextend` part of `lower.isle`](https://github.com/bytecodealliance/wasmtime/blob/270e92225da3acb5b0a583546b2d4598cb59ae2a/cranelift/codegen/src/isa/riscv64/lower.isle#L764-L795).

Although I think we might be missing some, like the `rolw` or `rorw` that sign extend the results.

And looking at the `uextend` rules we are also missing a bunch of them like `cpopw` / `clzw` / `ctzw`.

I don't know if it's better to have them next to `{s,u}extend` or their original ops since it might be easy to miss them where they are right now.

---

Edit: Maybe we could add a `maybe_sextend` / `maybe_uextend` matcher and then these rules could be folded into the regular `$I32` rules.

**Comment by afonso360** [comment]
It looks like the [OpenVINO installer may have an outdated package checksum](https://github.com/bytecodealliance/wasmtime/actions/runs/6379369760/job/17311713213#step:5:60). cc: @abrown

**Comment by alexcrichton** [comment]
Oh nice, I had totally missed those! Please feel free to do follow-ups, I was going to work on icmp next myself and it seems like you've got a good handle on what needs to fit in here.

This is interesting though because I'm taking inspiration from the [x64 backend for this PR](https://github.com/bytecodealliance/wasmtime/blob/270e92225da3acb5b0a583546b2d4598cb59ae2a/cranelift/codegen/src/isa/x64/inst.isle#L2220-L2233) where it pattern-matches a `Value` to skip an extension.

One point also possibly worth mentioning is that we may not, at this time, be able to put most of the logic here in `uextend` and `sextend` because extension is requested by many other instructions due to how the architecture works - this is why I wanted to refactor like this because now the backend can request extension outside of those CLIF instructions via `sext` and `zext`. That being said it's still a bit weird I think. At least the way it works on x64 is that during an extension operation no instructions are emitted for the operation being extended (e.g. an `addw` equivalent) but instead the choice to omit an extension instruction is made. This implicitly couples the lowering of 32-bit add plus a sign extension for example. This is not great because if the lowering for a 32-bit add changes then it may not be acompanied with an update to the optimization of skipping the sign extension. This has led to some possible optimizations being omitted in the x64 backend for example because the logic is too complicated to ensure they're in sync on "both halves". Basically I think this would be an interesting problem to solve, but as you've pointed out the `*w` instructions are simple enough to RISC-V it may be good enough to simply have all the lowerings in `sext` and `zext` and I think that should work out?

That would at least work out really well to avoid the problem of having two locations to keep in sync and instead only one has to be looked at.

**Comment by alexcrichton** [comment]
Alternatively I've also been musing lately due to all this if we should perhaps support target-specific rewrites of CLIF. One way to solve some of these issue is to simply remove lowerings that the backend doesn't support. For example RISC-V 64-bit doesn't support 32-bit comparisons (AFAIK at least) so a target-specific rewrite could change all comparisons to being 64-bit comparisons. Other misc examples include how there's no u8-to-f32 instruction on RISC-V so we're required to sign-extend to u32 and then convert. Doing at this at the CLIF layer would be quite nice since it could even benefit from egraph-based optimizations.

**Comment by afonso360** [comment]
I've had some thoughts about doing something similar but for a slightly different purpose. We have a lot of the unimplemented ops for `i128` in the various backends and building more complete support is a lot of work. Additionally most of them are fairly similar (`idiv.i128` is pretty much always going to be a libcall), so we could have the backend request expanded versions of the ops that they would know how to lower.

**Pull request merged**
