### PR TITLE
winch: Test winch against a subset of the official spec test suite

### PR DESCRIPTION
**Pull request by saulecabrera**
With the introduction of control flow, Winch is getting to a point in which it would be beneficial to have some sort of run tests rather than only filetests. Run tests make it easier to verify that the introduction of new features or bug fixes won't cause any regressions or bugs. They also make it easier to verify the behavior of the code generated by Winch.

The idea behind this change is to test Winch against a subset of the official spec test suite. Any unsupported tests will be commented out from the spec tests and as more features are added the corresponding tests will be uncommented. This involves a bit of duplication with regards to the spec tests, but the ideal end state is to have Winch be just another strategy in `build.rs` and have both compilers use `./tests/spec_testsuite` instead of using a custom directory for Winch once Winch offers feature parity.

Note that I'm currently collecting feedback on this idea, and for that reason, I've only included the block spec as an example. 

We discussed this idea during today's Winch meeting: https://github.com/bytecodealliance/meetings/blob/main/winch/2023/winch-06-20.md

@cfallin and @alexcrichton I'm interested in your thoughts regarding this change.

### CODE REVIEW

**Review by alexcrichton — COMMENTED** [review]
Glad to see Winch shaping up!

In the long run I don't think the test organization matters too too much as long as it's being tested, but in the interim one thing I might recommend is to "attempt" to run all tests with Winch but have `#[ignore]` on almost all of them. Similar to how riscv64 runs all the tests but skips anything simd related. That'd avoid having two copies of the tests and would attempt, by default, to run everything in Winch and Winch would have an allow-list that slowly grows or a deny-list that slowly gets smaller.

**Comment by alexcrichton** [comment]
I realize after writing that all out that you've probably already also considered such an idea, so I could also rephrase much of it as "I'm not sure why a copy of `block.wast` was added", but if that's well-motivated them seems fine!

**Comment by saulecabrera** [comment]
> I'm not sure why a copy of block.wast was added", but if that's well-motivated them seems fine!

Yeah, the copy of the spec tests is one of the unfortunate bits of this approach. Unfortunately attempting to run all the tests and adding `#[ignore]` when a non-supported feature is detected will result in most (if not all) of the official spec tests getting ignored, since as far as I can tell, there's no way to ignore spec tests at a more granular level. Even though Winch is shaping up, it doesn't offer support for finished proposals that are already part of the official spec suite, like multi-value for example, which many of the tests in the official spec test suite use. But it's totally possible that I might have missed a better way of avoiding the duplication, and if that's the case, I'm all in to explore alternatives!

**Comment by alexcrichton** [comment]
One idea perhaps would be to add a test for `strategy` in the `ignore` function against `"Winch"` and blanket return `true` (ignore everything) and then add a small allow-list for tests there? Or alternative blanket-ignore entire directories/subtrees but blanket-include others, for example `tests/misc_testsuite/winch/*.wast` could be tested in winch for now?

Otherwise though this is a transient state of affairs while support is shored up in winch so while I personally try to minimize the churn during the transient state I don't think it's bad to have churn and/or copies of files, so again I think whatever's easiest for your development should work best. In the long run everything should be run through both Winch/Cranelift and the "weird cases" will be much more defined.

**Comment by saulecabrera** [comment]
I finally got a chance to get back to this! I decided to try the approach of ignoring everything except for the `winch` misc test suite, I believe this will require the least amount of changes once we decide to enable everything by default in the future.

This should be ready for a review @alexcrichton; one thing to note is that I didn't add the `if` test suite yet, because I found one bug that I'm currently trying to figure out, once I do, I'll push the fix along with the test suite.

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
