### PR TITLE
wasi-sockets: Simplify & clarify TCP errors

### PR DESCRIPTION
**Pull request by badeend**
- Allow `accept()` to return transient errors.
  The original provision was added to align with preview3 streams that may only fail once. However, after discussing with Dan Gohman, we came to the conclusion that a `stream` of `result<>` could do the trick fine too.
    Fixes: https://github.com/WebAssembly/wasi-sockets/issues/22
- Fold `ephemeral-ports-exhausted` into `address-in-use`. There is no cross-platform way to know the distinction between them.
- Remove `concurrency-conflict` clutter,
  and just document it to be always possible.
- Simplify "not supported", "invalid argument" and "invalid state" error cases.
  There is a myriad of reasons why an argument might be invalid or an operation might be not supported. But there is few cross platform consistency in which of those error cases result in which error codes. Many wasi-sockets codes were unnecessarily detailed and had no standardized equivalent in POSIX, so wasi-libc will probably just map them all back into a single EOPNOTSUPP or EINVAL or ...
- Remove create-tcp/udp-socket not supported errors.
  These stem from back when the entire wasi-sockets proposal was one big single thing. In this day and age, when an implementation doesn't want to support TCP and/or UDP, it can simply _not_ implement that interface, rather than returning an error at runtime.
- Document that `connect` may return ECONNABORTED
- Clarify `connect` failure state:
```md
	POSIX mentions:
	> If connect() fails, the state of the socket is unspecified. Conforming applications should
	> close the file descriptor and create a new socket before attempting to reconnect.

	WASI prescribes the following behavior:
	- If `connect` fails because an input/state validation error, the socket should remain usable.
	- If a connection was actually attempted but failed, the socket should become unusable for further network communication.
```
- Clarify `local-address` behavior on unbound socket:
```md
POSIX mentions:
> If the socket has not been bound to a local name, the value
> stored in the object pointed to by `address` is unspecified.

WASI is stricter and requires `local-address` to return `not-bound` when the socket hasn't been bound yet.
```

### Additionally
- Document the set of socket options that are inherited through `accept`
- Added Linux, MacOS & Windows specific fixes.
- Added integration tests
- Move example_body out of lib.rs into `tcp_sample_application.rs` to make room for other tests.
- Keep track of the address family & IPV6_V6ONLY ourselves. This is used in various places to provide cross-platform behavior.
- Fix get/set_unicast_hop_limit. It didn't work for IPv4 sockets on Linux because Linux returns `OPNOTSUPP` instead of `NOPROTOOPT`.
- Use `Rustix::Errno` to base all error code checks on.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Given the crop of new tests I might recommend pushing a commit with `prtest:full` in the commit message to run full CI on this PR ahead of the merge queue, as this likely runs a risk of needing fixes for platform compatibility and such.

**Comment by alexcrichton** [comment]
(also thank you so much for writing these tests, it's very much appreciated!)

**Comment by alexcrichton** [comment]
Ah yeah looks like there's some issues on macOS at least. If you need help debugging I can see if I can pitch in, otherwise let me know when this is ready and I'll review for merge

**Comment by badeend** [comment]
Or is there a way to trigger *just* the MacOS CI?

**Comment by alexcrichton** [comment]
[This is the script](https://github.com/bytecodealliance/wasmtime/blob/main/ci/build-test-matrix.js) that determines what to run in CI, but running just macOS won't affect too much as it should start immediately. We should have enough parallelism on the org to run all builds each time, so no worries on that.

Otherwise one thing you can do is to edit CI to just run your single test (e.g. update `./ci/run-tests.sh` with a `cargo test` for just the test you're intersted in). Overall though it's unfortunately not fun debugging on hardware you don't have access to locally :(

**Comment by badeend** [comment]
@alexcrichton All tests turned green. I think this is ready for review now.

**Review by alexcrichton — APPROVED** [review]
Thanks!

**Pull request merged**
