### PR TITLE
Enable all aarch64 features in QEMU CI runner, except PAC

### PR DESCRIPTION
**Pull request by afonso360**
See #3322 for context

### CODE REVIEW

**Comment by afonso360** [comment]
CI Passes, but I think that's a false positive, it looks like [QEMU is segfaulting](https://github.com/bytecodealliance/wasmtime/pull/3325/checks?check_run_id=3565473980#step:12:1270).

**Comment by sparker-arm** [comment]
> CI Passes, but I think that's a false positive, it looks like [QEMU is segfaulting](https://github.com/bytecodealliance/wasmtime/pull/3325/checks?check_run_id=3565473980#step:12:1270).

This isn't an issue with this patch though, I think you'll find the same thing happening if you look in any of the recent other patches too.

**Comment by alexcrichton** [comment]
Hm that does look a little worrisome, but is it something that's known to be a failure? Our test suite triggers lots of segfaults which end up being caught, so I'm not sure if QEMU is printing the segfault and then we catch it or what. Also QEMU doesn't entirely exit because the test suite keeps running, so if it all runs to completion I'm not sure what the segfault message is actually pointing to.

**Comment by akirilov-arm** [comment]
I realize that you started this patch with a narrow scope, but how about upgrading to QEMU 6.1.0 as well - should be a simple change? From an AArch64 perspective the biggest advantage is IMHO SVE2 support.

**Comment by afonso360** [comment]
Yeah, sounds good.

It should also eventually allow us to add the s390x runner, since it looks like the issues with s390x are fixed in 6.1.0

**Comment by alexcrichton** [comment]
I double-checked the current builds we have and they don't have qemu printing out anything related to a segfault, which is somewhat worrisome. Would you be able to do a binary search on enabled features here to see which one is causing the segfault messages to appear? I still don't know how to interpret them because emulation continues to success but if we know which feature is causing the fault we may be able to disable it or debug further?

**Comment by afonso360** [comment]
Are you sure? I'm seeing the segfaults on the latest PR we merged ([here](https://github.com/bytecodealliance/wasmtime/runs/3599873098#step:12:1272))

**Comment by alexcrichton** [comment]
Oops I think I must have checked the wrong logs, I see them now. *shakes fist at GitHub Actions UI*

**Pull request merged**
