### PR TITLE
Release Wasmtime 0.32.0

### PR DESCRIPTION
**Pull request by wasmtime-publish**
This is an automated pull request from CI which is intended to
notify maintainers that it's time to release Wasmtime version
0.32.0. Version numbers have been bumped
in this PR automatically and the release process will automatically
enter the next stages once this PR is merged.

It's recommended that maintainers double-check that [RELEASES.md]
is up-to-date. If not please feel free to push to this PR any
modifications to the release notes. Additionally before merging it's
probably best to double-check the [release process] and make sure that
everything is ship-shape.

[RELEASES.md]: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md
[release process]: https://docs.wasmtime.dev/contributing-release-process.html

### CODE REVIEW

**Comment by fitzgen** [comment]
I think we should wait on https://github.com/bytecodealliance/wasmtime/pull/3585 getting fixed before doing our next release.

**Comment by cfallin** [comment]
+1 to that; uncomfortable releasing with a potential codegen issue.

**Comment by cfallin** [comment]
It looks like an issue with `iadd_ifcout`; the lowering only returns the add result, but it's supposed to be both the add result and the carry flag.

I pushed an update to the assertion to [the same branch in my fork](https://github.com/cfallin/wasmtime/tree/assert-tmp-dsts) (it was asserting just for one dst, not for all, but it's still a mismatch). Will look at the lowering, maybe it's simple to fix, otherwise we can just back out `iadd_ifcout` from ISLE for now to allow the release, I think.

**Comment by cfallin** [comment]
Further interesting twists: `iadd_ifcout` in the pre-ISLE world also wrote only to its first output (the add result) when lowered by itself. We have a separate pattern-match when `iadd_ifcout` is used by a `trapif` to explicltly do the right thing. As I recall, this special-casing is just enough to get the dynamic heap checks to work, and since we eventually want `iflags`-type values to be replaced by bools and pattern-matching, I don't think we want to fully reify the `iflags` in ISLE. Probably the best option is to just return a freshly-allocated second temp for the flags for now; anything that uses `iflags` will not be handled by ISLE so we will not be in danger of actually using it.

**Comment by cfallin** [comment]
Err, sorry, just realized I had written the above two comments on the wrong issue; will copy-paste over to the assertion issue and delete here.

**Comment by alexcrichton** [comment]
With #3585 landed is this otherwise good-to-go? If so I can try to update the release notes today as well before merging.

**Comment by cfallin** [comment]
I think so, yes!

**Comment by fitzgen** [comment]
Yeah, I think we are good to go now.

**Review by alexcrichton — APPROVED** [review]
Ok I added some release notes and will merge when this is ready on CI

**Pull request merged**
