### PR TITLE
Allow using virtual files for stdin/out/err

### PR DESCRIPTION
**Pull request by CryZe**
This adds the ability to use virtual files not only for the file system in WASI, but also for stdin, stdout and stderr.

### CODE REVIEW

**Comment by kubkon** [comment]
Hmm, I think this might be a potential duplicate of #1600.

**Comment by CryZe** [comment]
Oh, you are right, that is indeed seemingly solving the same problem. Feel free to close this one then if the (apparently much more complex) approach there is the better long term one.

**Comment by kubkon** [comment]
> Oh, you are right, that is indeed seemingly solving the same problem. Feel free to close this one then if the (apparently much more complex) approach there is the better long term one.

I think we should hold off with the decision until there's a decision about #1561. If that one lands, then given all the design changes introduced to `wasi-common`, it'll make sense to close this one in favour of #1600. However, if we decide not go with #1561, then I'll be happy to land your fix instead. Oh, and thanks a lot for the PR! It's much appreciated! :-)

**Comment by whitequark** [comment]
Looks like #1561 did land.

**Comment by kubkon** [comment]
Thanks for the PR @CryZe. Since we’ve decided to go with #1600, this PR has now been superseded so I’ll go ahead and close it.

**Pull request closed without merging**
