### PR TITLE
Add support for vector in DataValueExt::int()

### LINKED ISSUE #6827: Cranelift: SIMD `ineg` crashes the interpreter
👋 Hey,

### `.clif` Test Case

```
test interpret

function %simd_ineg_i64x2(i64x2) -> i64x2 {
block0(v0: i64x2):
    v1 = ineg v0
    return v1
}
; run: %simd_ineg_i64x2([0 1]) == [0 -1]
```

### Steps to Reproduce

* `cd cranelift`
* `cargo run -- test ./the-above.clif`

### Expected Results

The test to pass!

### Actual Results

```
 ERROR cranelift_filetests::concurrent > FAIL: interpret
FAIL ./lmao.clif: interpret

Caused by:
    unexpected trap: StepError(ValueError(InvalidType(Integer, types::I64X2)))
1 tests
Error: 1 failure
```

It looks like the [`ineg` instruction in the interpreter](https://github.com/bytecodealliance/wasmtime/blob/f32993002bc523083b7d7cca49179a3285c44c03/cranelift/interpreter/src/step.rs#L656) is implemented for scalar values but not for SIMD!

### Versions and Environment

Cranelift version or commit: main

Operating system: Linux

Architecture: X86_64 (but it could be any really!)

### Extra Info

I would suspect that this goes wrong in `DataValueExt::int(0, ctrl_ty)`, that operation seems to not be ready to produce SIMD values. We could change that and it might work!

If anyone needs help working on this let me know!

### PR DESCRIPTION
**Pull request by gurry**
Fixes #6827

### CODE REVIEW

**Comment by gurry** [comment]
`DataValueExt::int()` doesn't currently seem to have any tests. Please let me know if I should add any tests for this PR or for `DataValueExt::int()` in general.

**Comment by gurry** [comment]
Just saw that the test already exists:

https://github.com/bytecodealliance/wasmtime/blob/30d086f78e1e53cc52f3918aba3edf397d98b6d7/cranelift/filetests/filetests/runtests/simd-ineg.clif#L30-L35 

So just enabled it for the interpreter.

**Review by afonso360 — APPROVED** [review]
👋 Hey,

This looks great! Thanks!

> DataValueExt::int() doesn't currently seem to have any tests. Please let me know if I should add any tests for this PR or for DataValueExt::int() in general.

Yeah, we usually test the opcodes via clif tests instead of the internals, so enabling the `ineg` tests is great!

**Comment by afonso360** [comment]
> While the interpreter worked fine, it was the compiler that crashed. Is this expected?

Well, sort of. Ideally we would be able to compile all clif code, but 64 bit SIMD support is *very* incomplete both in the backends and in the interpreter itself. The only architectures that support it are AArch64 and RISC-V.

I think X86_64 has never supported it, so yeah I would expect it to crash there.

**Comment by gurry** [comment]
Okay, makes sense. Thanks 👍

**Pull request merged**
