### PR TITLE
Fix build on 32-bit Windows; consolidate CI platform checks

### LINKED ISSUE #4434: Failed to build for `i686-pc-windows-msvc`
File [`winx32.rs`](https://github.com/bytecodealliance/wasmtime/blob/main/crates/jit/src/unwind/winx32.rs) is outdated.

```
error[E0433]: failed to resolve: use of undeclared crate or module `cranelift_codegen`
 --> C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmtime-jit-0.38.1\src\unwind\winx32.rs:4:5
  |
4 | use cranelift_codegen::isa::{unwind::UnwindInfo, TargetIsa};
  |     ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `cranelift_codegen`

error[E0432]: unresolved import `crate::unwind::UnwindRegistration`
 --> C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmtime-jit-0.38.1\src\code_memory.rs:3:5
  |
3 | use crate::unwind::UnwindRegistration;
  |     ^^^^^^^^^^^^^^^------------------
  |     |              |
  |     |              help: a similar name exists in the module: `UnwindRegistry`
  |     no `UnwindRegistration` in `unwind`

Some errors have detailed explanations: E0432, E0433.
```

### LINKED ISSUE #9882: 32bit Windows target support (now that we have Pulley)
Now that we have Pulley, we're keen to get wasmtime working on 32 bit Windows. My assumption here is that this is in roadmap?

Today, if you build wasmtime and target i686-pc-windows-msvc or i686-pc-windows-gnu, the compiler complains. I'm assuming that the fix should be relatively minimal but I'm not familiar with wasmtime internals.

What is the lift here?

```
cargo run  --target=i686-pc-windows-gnu
   Compiling wasmtime v29.0.0 (/XXX/wasmtime/crates/wasmtime)
error: unsupported platform
   --> /XXX/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/traphandlers.rs:113:17
    |
113 |                 compile_error!("unsupported platform");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `crate::runtime::vm::HostAlignedByteCount`
 --> /XXX/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/mmap.rs:3:26
  |
3 | use crate::runtime::vm::{HostAlignedByteCount, SendSyncPtr};
  |                          ^^^^^^^^^^^^^^^^^^^^ no `HostAlignedByteCount` in `runtime::vm`

error[E0425]: cannot find value `regs` in this scope
   --> /XXX/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/traphandlers.rs:126:33
    |
126 |         match info.test_if_trap(regs, faulting_addr, |handler| handler(exception_info)) {
    |                                 ^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `RtlAddFunctionTable` in this scope
  --> /XXX/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/unwind.rs:30:12
   |
30 |         if RtlAddFunctionTable(
   |            ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function, tuple struct or tuple variant `RtlDeleteFunctionTable` in this scope
  --> /XXX/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/unwind.rs:48:13
   |
48 |             RtlDeleteFunctionTable(self.functions as _);
   |             ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `wasmtime` (lib) due to 5 previous errors
```

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes the build of the `wasmtime` crate and CLI on 32-bit Windows. This required adding some extra bits for trap handling and a stub for "unimplemented" for unwind information registration. This then additionally refactored our CI configuration to place all of the cross-compile checks in one matrix instead of spread out across a few jobs.

Closes #4434
Closes #9882

### CODE REVIEW

**Review by pchickey — APPROVED** [review]

**Comment by alexisvincent** [comment]
Fixes all except:

```
error[E0432]: unresolved import `crate::runtime::vm::HostAlignedByteCount`
 --> /xxx/wasmtime/crates/wasmtime/src/runtime/vm/sys/windows/mmap.rs:3:26
  |
3 | use crate::runtime::vm::{HostAlignedByteCount, SendSyncPtr};
  |                          ^^^^^^^^^^^^^^^^^^^^ no `HostAlignedByteCount` in `runtime::vm`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wasmtime` (lib) due to 1 previous error
```

**Comment by alexcrichton** [comment]
@alexisvincent I'm having a tough time reproducing that locally and I'm not sure why... Can you share what the dependency directive in `Cargo.toml` looks like for `wasmtime`? (unsure which features you have active)

**Comment by alexisvincent** [comment]
> @alexisvincent I'm having a tough time reproducing that locally and I'm not sure why... Can you share what the dependency directive in `Cargo.toml` looks like for `wasmtime`? (unsure which features you have active)

Get it for `--target=i686-pc-windows-gnu`:
```
[dependencies.wasmtime]
path = "../../vendor/wasmtime/crates/wasmtime"
default-features = false
features = [
  "runtime"
]
```

Ill see if I can get a repro

**Comment by alexcrichton** [comment]
Ah no yep that works, thanks! I tried every combo but that, don't know why I didn't try the most obvious combo to start...

**Pull request merged**
