### PR TITLE
cranelift: Added `bitcast.f32` for i32, `bitcast.f64` for i64 to interpreter.

### PR DESCRIPTION
**Pull request by ArtBlnd**
@afonso360 
Related to https://github.com/bytecodealliance/wasmtime/pull/4920

### CODE REVIEW

**Review by afonso360 — APPROVED** [review]
LGTM! Thanks!

**Comment by ArtBlnd** [comment]
Also looks `bitcast.{i32, i64}` for fp types are missing. I'll add it later when its merged.

**Comment by akirilov-arm** [comment]
This looks like a duplicate of @dheaton-arm's PR #4820.

**Comment by ArtBlnd** [comment]
> This looks like a duplicate of @dheaton-arm's PR https://github.com/bytecodealliance/wasmtime/pull/4820. 
oh... yeah I didn't know about that. I'm closing pr.

**Comment by ArtBlnd** [comment]
but still I think that should be seperated.

**Pull request closed without merging**
