### PR TITLE
Add release binaries for x86_64-musl

### PR DESCRIPTION
**Pull request by alexcrichton**
This was requested in bytecodealliance/wasmtime-py#237 and shouldn't cost us too much in terms of CI resources and maintenance overhead.

### CODE REVIEW

**Review by elliottt — APPROVED** [review]

**Comment by whitequark** [comment]
Thanks again =^__^=

This will improve the compatibility story for YoWASP and the Glasgow Interface Explorer to even more Linux distributions.

**Comment by aambrose-sonatus** [comment]
Hi @alexcrichton, I'm curious about a couple things here regarding musl support:
1. What is the wasmtime dependency on libgcc? Is this something core, or just how the toolchain is structured right now?
2. What is the limitation that is preventing wasmtime from being fully static with musl libraries? Is it the above libgcc dep?

Thank you

**Comment by bjorn3** [comment]
For usage in C we compile a wasmtime.so. Producing a dynamic library is incompatible with statically linking libc. The musl based binaries also seem to be meant for usage on musl based distros where statically linking libc only has disadvantages. (bigger binaries, not getting security updates to libc)

**Comment by aambrose-sonatus** [comment]
Is there anything that precludes compiling the static library version of the embedding (IE `libwasmtime.a`) as fully static? Perhaps not as an official release artifact, but e.g. when compiling from source oneself or when using wasmtime as a crate dependency for some other binary?

**Comment by bjorn3** [comment]
If you compile it yourself, I don't see why it shouldn't work.

**Comment by aambrose-sonatus** [comment]
Yeah it seemed to be working on my end; I used zig as the C toolchain so I get full static outputs by default. My questions were more regarding the statement `they are not suitable for "run on any linux distribution" style use cases` and whether this applied to all source builds, or only the publicly released artifacts. It sounds like it's the latter.

Thank you both!

**Pull request merged**
