### PR TITLE
feat: remove the limitation of either R or W polls

### PR DESCRIPTION
**Pull request by haraldh**
Allow polls on read _and_ write.

See also https://github.com/tokio-rs/mio/pull/1549#discussion_r814650539

Why was this limitation added?

Signed-off-by: Harald Hoyer <harald@profian.com>

### CODE REVIEW

**Comment by pchickey** [comment]
It appears that 7a1b7cd changed this code from the Poll structure holding mutable refs to a WasiFile to having a shared ref, so this used-at-most-once check is no longer necessary.

**Review by pchickey — APPROVED** [review]
This code was made unnecessary by the RFC11 refactor but we didn't catch it during code review.

**Review by sunfishcode — APPROVED** [review]
I agree. With the way __wasi_poll_oneoff currently works, it should be able to handle the same file descriptor appearing multiple times.

**Comment by pchickey** [comment]
Thanks @haraldh !

**Pull request merged**
