### PR TITLE
Improve code generation for floating-point constants

### PR DESCRIPTION
**Pull request by FreddieLiardet**
Use fmov immediate version where possible.

Copyright (c) 2022, Arm Limited.

### CODE REVIEW

**Review by cfallin — COMMENTED** [review]
Thanks for working on this!

The changes look mostly reasonable, but I have one high-level question: I don't see any additions to `aarch64/lower.isle`, and looking at the current version of that file, nothing is handling f32const/f64const that I can see. I'm actually quite surprised that removing those cases from the handwritten code (`lower_inst.rs`) doesn't break any tests; I guess we don't have coverage for simple fconst instructions...? (If we did, I'd expect to see cases where we can use `fmov` and cases where we can't added here as well.)

It's possible that I'm missing something though! But if not -- did you mean to use the new instruction added in the lowering patterns?

**Comment by alexcrichton** [comment]
I think this path in lowering was never actually hit due to roughly [this block of code](https://github.com/bytecodealliance/wasmtime/blob/1ef0abb12c1978a96b2dd7299390dbe204a138d7/cranelift/codegen/src/machinst/lower.rs#L1221-L1241). My hope was to eventually reimplement the `gen_constant` method with an ISLE-based lowering eventually but I figured it may also be pretty tricky to do so.

**Comment by FreddieLiardet** [comment]
I have added some more tests for simple f32/64const cases. 

> I think this path in lowering was never actually hit due to roughly [this block of code](https://github.com/bytecodealliance/wasmtime/blob/1ef0abb12c1978a96b2dd7299390dbe204a138d7/cranelift/codegen/src/machinst/lower.rs#L1221-L1241).

Yes I think this is the case.

**Comment by cfallin** [comment]
> I think this path in lowering was never actually hit due to roughly this block of code

Ah, yes, this is the bit I had forgotten... we should never see an F32const/F64const value at the top-level lowering entry point, because either it is used somewhere and rematerialized at every use, or never used and hence dropped by the implicit DCE (use-counting). The existing top-level handlers for F32const/F64const were written before the rematerialize-at-uses change was made, I think.

@FreddieLiardet given this, the change I think doesn't have to touch ISLE at all, since we haven't yet moved constant generation over. Could you:

* Remove the addition to `inst.isle` (we don't need to define variants of `MachInst` in the ISLE prelude that we don't use)
* Change the F32const/F64const lowering entry points from `implemented_in_isle!()` to a panic saying something like "Should never see constant ops at top-level lowering entry point, as constants are rematerialized at use-sites"

Then I think this should be good to merge -- thanks!

**Comment by FreddieLiardet** [comment]
@cfallin I am unsure about the first point. Is there another place where `FpuMoveFPImm` instruction should be declared?  This instruction is used throughout this change.

**Comment by cfallin** [comment]
@FreddieLiardet ah, my apologies, I was out-of-sync with our transition: we had previously defined the `Inst` enum in plain Rust and declared the enum arms we needed separately in ISLE, but I had forgotten that we now generate the enum itself from ISLE. So your diff to add the instruction here is good (modulo the generated-code merge conflict, which you should be able to resolve by rebasing).

**Review by cfallin — APPROVED** [review]
Thanks -- this looks good now after changes!

**Pull request merged**
