### PR TITLE
x64: Add native lowering for scalar `fma`

### PR DESCRIPTION
**Pull request by afonso360**
👋 Hey

This PR adds a lowering for scalar `fma` for x64. Additionally we enable this operation in the CLIF Fuzzer.

cc: @abrown

### CODE REVIEW

**Comment by jameysharp** [comment]
This PR has unfortunately gone stale, but I'd like to not lose track of it. @afonso360, could you give it a rebase?

**Comment by afonso360** [comment]
Changes with the last rebase:

* We now query the `use_fma` flag to lower FMA extension instructions
* Added some compile for both the libcall and inst case

**Comment by afonso360** [comment]
CI failures seem spurious

**Review by elliottt — APPROVED** [review]
This looks great to me! Thanks for adding all the filetest cases!

**Comment by jameysharp** [comment]
CI failures are because today's release of Rust 1.63 reports a new warning. #4691 is merged fixing that, so please rebase and then hopefully CI will pass.

**Pull request merged**
