### PR TITLE
Add async example to bindgen_examples

### LINKED ISSUE #9776: Missing examples for using bindgen! async, imports and resource in host
#### Feature

There are no examples about using `bindgen!` with `async: true`, imports and resources in Rust hosts. Please add examples to do that. 

#### A bit of background

I have a `string.wit` and a guest component.

```
package component:big-string;


interface large-string {
  resource largestring {
    constructor();
    push: func(s: string);
    get: func() -> string;
    clear: func();
  }
}

world big-string {
  import large-string;
  import print: func(s: string) -> bool;
  export manipulate-large-string: func() -> string;
}

```

I want to run this component in a Rust host. It took me quite a while to debug and inspect the generated code with `cargo-expand` to implement this. The code is much more complicated than the and there's no way for IDE to help. 

I didn't have any clues how to write the code until I cargo-expanded the macro.

You should at least add an example in [bindgen_example](https://docs.rs/wasmtime/latest/wasmtime/component/bindgen_examples/index.html) to give a first impression to newcomers about the complexity.

And probably you can simplify the traits of the async version with latest Rust async functions in traits.

#### Benefit

* Adding an example in [bindgen_example](https://docs.rs/wasmtime/latest/wasmtime/component/bindgen_examples/index.html) can give a first impression to newcomers about the complexity
* Probably simplifying it in bindgen with latest Rust async functions in traits can ultimately remove these annoying lifetimes, `Pin` and `Box` in function signatures, which will enable IDE to autocomplete and help better.

#### Implementation

I can make a PR to submit my code to be an example.

#### Full Code

```rust
use crate::utils::get_component_linker_store;
use crate::utils::{bind_interfaces_needed_by_guest_rust_std, ComponentRunStates};
use wasmtime::component::bindgen;
use wasmtime::component::Resource;
use wasmtime::Engine;


mod sync_version {
    use super::*;

    bindgen!({
        path: "../wit-files/string.wit",
        world: "big-string",
        with: {
            "component:big-string/large-string/largestring": LargeString
        }
    });

    pub struct LargeString {
        pub storage: String,
    }

    impl BigStringImports for ComponentRunStates {
        fn print(&mut self, string: String) -> bool {
            println!("from print sync host func: {}", string);
            true
        }
    }

    impl component::big_string::large_string::Host for ComponentRunStates {}

    impl component::big_string::large_string::HostLargestring for ComponentRunStates {
        fn new(&mut self) -> Resource<LargeString> {
            self.resource_table
                .push(LargeString {
                    storage: String::new(),
                })
                .unwrap()
        }

        fn push(&mut self, resource: Resource<LargeString>, s: String) -> () {
            let large_string = self.resource_table.get_mut(&resource).unwrap();
            large_string.storage.push_str(s.as_str());
        }

        fn get(&mut self, resource: Resource<LargeString>) -> String {
            let large_string = self.resource_table.get(&resource).unwrap();
            format!("sync: {}", large_string.storage)
        }

        fn clear(&mut self, resource: Resource<LargeString>) -> () {
            let large_string = self.resource_table.get_mut(&resource).unwrap();
            large_string.storage.clear();
        }

        fn drop(&mut self, resource: Resource<LargeString>) -> wasmtime::Result<()> {
            let _ = self.resource_table.delete(resource)?;
            Ok(())
        }
    }
}

mod async_version {
    use futures::executor::block_on;

    use super::*;
    use core::future::Future;
    use core::pin::Pin;

    bindgen!({
        path: "../wit-files/string.wit",
        world: "big-string",
        async: true,
        with: {
            "component:big-string/large-string/largestring": LargeString
        },
    });

    pub struct LargeString {
        pub storage: String,
    }

    impl BigStringImports for ComponentRunStates {
        fn print<'life, 'async_trait>(
            &'life mut self,
            s: String,
        ) -> Pin<Box<dyn Future<Output = bool> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            // TODO: make a PR for this
            Box::pin(async move {
                println!("from print async host func: {}", s);
                true
            })
        }
    }

    impl component::big_string::large_string::Host for ComponentRunStates {}

    impl component::big_string::large_string::HostLargestring for ComponentRunStates {
        fn new<'life, 'async_trait>(
            &'life mut self,
        ) -> Pin<Box<dyn Future<Output = Resource<LargeString>> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            Box::pin(async {
                self.resource_table
                    .push(LargeString {
                        storage: String::new(),
                    })
                    .unwrap()
            })
        }

        fn push<'life, 'async_trait>(
            &'life mut self,
            resource: Resource<LargeString>,
            s: String,
        ) -> Pin<Box<dyn Future<Output = ()> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            Box::pin(async move {
                let large_string = self.resource_table.get_mut(&resource).unwrap();
                large_string.storage.push_str(s.as_str());
            })
        }

        fn get<'life, 'async_trait>(
            &'life mut self,
            resource: Resource<LargeString>,
        ) -> Pin<Box<dyn Future<Output = String> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            Box::pin(async move {
                let large_string = self.resource_table.get(&resource).unwrap();
                format!("async: {}", large_string.storage)
            })
        }

        fn clear<'life, 'async_trait>(
            &'life mut self,
            resource: Resource<LargeString>,
        ) -> Pin<Box<dyn Future<Output = ()> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            Box::pin(async move {
                let large_string = self.resource_table.get_mut(&resource).unwrap();
                large_string.storage.clear();
            })
        }

        fn drop<'life, 'async_trait>(
            &'life mut self,
            resource: Resource<LargeString>,
        ) -> Pin<Box<dyn Future<Output = wasmtime::Result<()>> + Send + 'async_trait>>
        where
            'life: 'async_trait,
            Self: 'async_trait,
        {
            Box::pin(async {
                let _ = self.resource_table.delete(resource)?;
                Ok(())
            })
        }
    }

}
```

### PR DESCRIPTION
**Pull request by ifsheldon**
Closes #9776

I reused most of example 4 to avoid extra complication. Also adds a reference to code example `wasi_async`, so it'd better if this gets merged after #9788.

cc @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks, and looks good to me! I think there's some errors on CI though?

**Comment by ifsheldon** [comment]
Can you take a look into the clippy error please? The error seems to originate from `bindgen!`. I suspect that some code in `bindgen!` forgets to import `Box` when a WIT spec is inlined. In my own example that imports from a WIT file, there's no problem. In the example 4 where async is not used, it's also fine. I have no clue why that happened. The difference between `_7_async.rs` and `_4_imported_resources.rs` is just the line `async: true,`

**Comment by alexcrichton** [comment]
Ah I believe this is exposing a preexisting bug in the `bindgen!` macro, notably the async output is not compatible with `#![no_std]` crates. The `wasmtime` crate itself is such a crate which is where this is coming from. 

I'm not sure of a way to work around this other than fixing the issue at hand (tracking down the `Box` and importing it from `wasmtime::component::__internal::Box`)

**Comment by ifsheldon** [comment]
I think for the purpose of documentation, it's okay to let clippy skip this file. 

> this is exposing a preexisting bug in the bindgen! macro, notably the async output is not compatible with #![no_std] crates. The wasmtime crate itself is such a crate which is where this is coming from.

IIUC, #9823 maybe unblock this?

> I'm not sure of a way to work around this other than fixing the issue at hand 

Can you try to fix this please? I'm not very familiar proc_macros or bindgen internals.

**Comment by alexcrichton** [comment]
Yes #9823 would probably help. Unfortunately I don't have time right now to fix this myself, and this can't land unless it's passing CI.

**Comment by ifsheldon** [comment]
OK...... Can you find the issue tracking the "preexisting bug" you mentioned? I can't find one to link here. Or, I can file a new one.

**Comment by alexcrichton** [comment]
I don't believe there's a preexisting issue since this is I think the first time it's come up, but feel free to file an issue of course

**Comment by ifsheldon** [comment]
OK, let's take a step back. Why need to build bindgen_examples inside `wasmtime` anyway? I think we can just move all the bindgen examples out of `wasmtime` crate.

**Comment by alexcrichton** [comment]
It's not necessarily strictly required, but it's quite useful to be distributed as part of docs.rs integration. That gives nice API docs all in one place. Personally I think it'd probably be less effort to fix the code generation than it would be to move all the documentation somewhere else.

**Comment by alexcrichton** [comment]
Thanks! I think some test expectations may need an update, but otherwise looks good 👍

**Pull request merged**
