### PR TITLE
winch(trampolines): Save SP, FP and return address

### PR DESCRIPTION
**Pull request by saulecabrera**
This change is a follow-up to https://github.com/bytecodealliance/wasmtime/pull/6358

This change implements the necessary stores of SP, FP and return address for fast stack walking.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
I think that failure may be a bug with github's merge queue...

**Comment by saulecabrera** [comment]
Oh that makes sense; I was taking a look to see if it was a failure due my changes, but all jobs were marked as cancelled.

**Comment by saulecabrera** [comment]
Yep, I see it; I'll take a look!

**Comment by saulecabrera** [comment]
I spent some time debugging this issue and it's indeed legitimate. The root cause of the failure in MSVC is the lack of unwind info, which as far as I understand is required in Windows; I can reproduce the exact same failure by disabling the unwind info generation in Cranelift. I'm working on a separate PR to add support for emitting unwind info in Winch.

**Comment by saulecabrera** [comment]
Sounds good, yeah, I'll ignore them to land this PR and put them back when introducing support for the emitting unwind info.

**Pull request merged**
