### PR TITLE
Support plugging external profilers into the Cranelift timing infrastructure

### PR DESCRIPTION
**Pull request by bjorn3**
This for example allows plugging in an adapter for rustc's measureme profiler allowing details for both rustc and Cranelift to be present in a single profile. Measureme has several tools that process profiles. The flamegraph tool for example produced the following flamegraph:

rustc

(Download the svg and open it to make it interactive. Github's CSP policy prevents executing javascript.)

### CODE REVIEW

**Comment by bjorn3** [comment]
This is the code necessary on cg_clif's side for this:

```rust
struct MeasuremeProfiler(SelfProfilerRef);

struct TimingGuard {
    profiler: std::mem::ManuallyDrop<SelfProfilerRef>,
    inner: Option<rustc_data_structures::profiling::TimingGuard<'static>>,
}

impl Drop for TimingGuard {
    fn drop(&mut self) {
        self.inner.take();
        unsafe {
            std::mem::ManuallyDrop::drop(&mut self.profiler);
        }
    }
}

impl cranelift_codegen::timing::Profiler for MeasuremeProfiler {
    fn start_pass(
        &self,
        pass: cranelift_codegen::timing::Pass,
    ) -> Box<dyn std::any::Any> {
        let mut timing_guard = TimingGuard {
            profiler: std::mem::ManuallyDrop::new(self.0.clone()),
            inner: None,
        };
        timing_guard.inner = Some(
            unsafe {
                &*(&*timing_guard.profiler as &SelfProfilerRef
                    as *const SelfProfilerRef)
            }
            .generic_activity(pass.description()),
        );
        Box::new(timing_guard)
    }
}

cranelift_codegen::timing::set_thread_profiler(Box::new(MeasuremeProfiler(
    cx.profiler.clone(),
)));
```

Most of it deals with a lifetime issue on measureme's side.

**Comment by bjorn3** [comment]
Measureme also supports outputting chrome profiler profiles, but chrome's profiler seems to suffer from float rounding errors causing some issues.

**Comment by jameysharp** [comment]
I've reviewed everything in this PR except the most important commit ("Introduce a Profiler trait"), which I want to take a little longer to think about. I think it's a good idea! I just want to dig into the details.

Everything else I think is easy to approve: it's a bunch of good cleanups.

If you'd like to split that one commit to a separate PR I'd be happy to merge the rest now and either I or somebody else will review the Profiler trait parts later. But it's also okay if you'd like to just wait for it to all be reviewed and merged at once.

I'm not familiar with the measureme profiler. Is that something we could use in other Cranelift drivers like Wasmtime as well, or is it a module in rustc? I'd love to get flamegraphs like your demo for other uses of Cranelift as well.

**Comment by bjorn3** [comment]
> If you'd like to split that one commit to a separate PR I'd be happy to merge the rest now and either I or somebody else will review the Profiler trait parts later. But it's also okay if you'd like to just wait for it to all be reviewed and merged at once.

I'm fine with waiting until the entire PR is reviewed, but if you prefer a smaller PR I can split it out.

> I'm not familiar with the measureme profiler. Is that something we could use in other Cranelift drivers like Wasmtime as well, or is it a module in rustc? I'd love to get flamegraphs like your demo for other uses of Cranelift as well.

See https://github.com/rust-lang/measureme/. Having a measureme based profiler in Cranelift would be possible, but the `Profiler` interface is still necessary as it wouldn't be possible for Cranelift to use the exact same version of measureme as rustc without `#![feature(rustc_private)]`. Measureme is designed to be as low overhead as possible (the rustc benchmark suite runs with it enabled by default to allow for more detailed investigation.) It supports both wall time based and on x86 instruction based profiling. It supports both interval and instant events and allows extra metadata (like the name of the function being processed or the size of a compiled artifact).

**Comment by bjorn3** [comment]
@jameysharp gentle ping

**Review by jameysharp — APPROVED** [review]
Thanks for reminding me! Yes, this looks good.

I had some questions about why you made various things `pub` while reviewing the changes for the new `Profiler` trait, but realized they all had the same answer. In particular, `NUM_PASSES` is public now because it's useful for an implementation of `Profiler` to be able to pre-allocate space.

I think it would be nice if `DefaultProfiler` were defined in a separate module to make it obvious that everything necessary to implement the `Profiler` trait really is public. But at the same time I'm glad you didn't do that in this PR because it might have been harder to review that code movement. If you feel like opening another PR to make that change I'd be happy to take it.

**Comment by jameysharp** [comment]
Oh, I think you'll need to rebase before I can merge since the set of required CI jobs changed.

**Comment by bjorn3** [comment]
Rebased

> If you feel like opening another PR to make that change I'd be happy to take it.

Sure

**Comment by bjorn3** [comment]
cg_clif side of this implemented in https://github.com/bjorn3/rustc_codegen_cranelift/commit/ef07e8e60f994ec014d049a95591426fb92ebb79

**Pull request merged**
