### PR TITLE
Release Wasmtime 23.0.2

### PR DESCRIPTION
**Pull request by wasmtime-publish**
This is an [automated pull request][process] from CI to create a patch release for Wasmtime 23.0.2, requested by @alexcrichton.

It's recommended that maintainers double-check that [RELEASES.md] is up-to-date and that there are no known issues before merging this PR. When this PR is merged a release tag will automatically be created, crates will be published, and CI artifacts will be produced.

[RELEASES.md]: https://github.com/bytecodealliance/wasmtime/blob/release-23.0.2/RELEASES.md
[process]: https://docs.wasmtime.dev/contributing-release-process.html

### CODE REVIEW

**Comment by alexcrichton** [comment]
I believe @pchickey would like to do another backport as well, so I'll hold off on merging this until that's in as well.

**Review by pchickey — APPROVED** [review]

**Comment by sehz** [comment]
What about https://github.com/bytecodealliance/wasmtime/pull/9118/files?  This prevent us from upgrading.

**Comment by pchickey** [comment]
The backport of 9100 has landed in the release branch so it will be part of the release when this merges.

**Comment by sehz** [comment]
Great.  Thanks!

**Pull request merged**
