### PR TITLE
Release Wasmtime 2.0.0

### PR DESCRIPTION
**Pull request by wasmtime-publish**
This is an [automated pull request][process] from CI which is
intended to notify maintainers that it's time to release Wasmtime
2.0.0. The [release branch][branch] was created roughly two weeks ago
and it's now time for it to be published and released.

It's recommended that maintainers double-check that [RELEASES.md]
is up-to-date and that there are no known issues before merging this
PR. When this PR is merged a release tag will automatically be
created, crates will be published, and CI artifacts will be produced.

[RELEASES.md]: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md
[process]: https://docs.wasmtime.dev/contributing-release-process.html
[branch]: https://github.com/bytecodealliance/wasmtime/tree/release-2.0.0

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
I'll give this a few hours for folks to wake up and raise objections if there are any, otherwise I'll merge later this afternoon.

**Review by bjorn3 — APPROVED** [review]
Just checked the release-2.0.0 branch with cg_clif again. No regressions.

**Comment by bjorn3** [comment]
"Push tagged release" has finished, but "Publish on crates.io" hasn't even started yet. Did something go wrong?

**Comment by bjorn3** [comment]
Publishing cranelift-jit failed:

```
    Updating crates.io index
   Packaging cranelift-jit v0.89.0 (/home/runner/work/wasmtime/wasmtime/cranelift/jit)
error: failed to prepare local package for uploading
Caused by:
  failed to select a version for the requirement `cranelift-codegen = "^0.89.0"`
  candidate versions found which didn't match: 0.88.1, 0.88.0, 0.87.1, ...
  location searched: crates.io index
  required by package `cranelift-jit v0.89.0 (/home/runner/work/wasmtime/wasmtime/cranelift/jit)`
FAIL: failed to publish `cranelift-jit`: exit status: 101
```

and so did a couple of other crates like wasmtime-wasi-crypt:

```
Updating crates.io index
   Packaging wasmtime-wasi-crypto v2.0.0 (/home/runner/work/wasmtime/wasmtime/crates/wasi-crypto)
   Uploading wasmtime-wasi-crypto v2.0.0 (/home/runner/work/wasmtime/wasmtime/crates/wasi-crypto)
error: failed to publish to registry at https://crates.io/

Caused by:
  failed to get a 200 OK response, got 500
  headers:
  	HTTP/2 500
  	content-length: 21
  	server: nginx
  	date: Thu, 20 Oct 2022 19:23:00 GMT
  	strict-transport-security: max-age=31536000
  	via: 1.1 vegur, 1.1 61bbe72b71f7b857c695c31fdeb7b3a6.cloudfront.net (CloudFront)
  	x-cache: Error from cloudfront
  	x-amz-cf-pop: IAD12-P1
  	x-amz-cf-id: 6Fthgy-zFtAbTgb4rbN6JeMrC_wIfphMXuF5TPhc9Iuy7d_3FzExNw==
  	
  body:
  Internal Server Error
FAIL: failed to publish `wasmtime-wasi-crypto`: exit status: 101
```

**Pull request merged**
